// -----------------------------------------------------------------------
// <copyright file="CorpusManifest.cs" company="Aaron Stannard">
//      Copyright (C) 2026 - 2026 Aaron Stannard <https://github.com/Aaronontheweb>
// </copyright>
// -----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using ShellSyntaxTree;

namespace ShellSyntaxTree.Tools.PwshCorpus;

internal enum ManifestTransform
{
    None,
    EncodeCommand,
    OversizedInput,
}

/// <summary>One curated PowerShell corpus input (SPEC.POWERSHELL.md §13).</summary>
internal sealed record ManifestEntry(
    string Slug,
    string RawInput,
    string Notes,
    bool OutOfScope,
    ManifestTransform Transform,
    bool IncludeElements = false,
    bool IncludeStructure = false,
    bool IncludeOptionalAssertions = false,
    bool IncludeV03Assertions = false,
    string? DisplayName = null,
    PwshInitialStateMode? PowerShellInitialStateMode = null,
    PwshDialect? PowerShellDialect = null)
{
    /// <summary>Explicit display name when supplied; otherwise derived from the slug.</summary>
    public string Name =>
        DisplayName ?? (Slug.Length == 0
            ? Slug
            : char.ToUpperInvariant(Slug[0]) + Slug.Substring(1).Replace('_', ' '));

    /// <summary>The actual command string, after applying <see cref="Transform"/>.</summary>
    public string ResolveInput() => Transform switch
    {
        ManifestTransform.EncodeCommand =>
            "pwsh -EncodedCommand " + Convert.ToBase64String(Encoding.Unicode.GetBytes(RawInput)),
        ManifestTransform.OversizedInput =>
            RawInput + new string('a', 70 * 1024),
        _ => RawInput,
    };
}

/// <summary>
/// The hand-curated PowerShell corpus inputs. Each becomes an
/// <c>NNN_slug.json</c> entry under <c>Corpus/powershell/</c>; coverage
/// follows the SPEC.POWERSHELL.md §13 category table. The expected AST is
/// generated from <see cref="ShellSyntaxTree.PwshParser"/>; the real-pwsh
/// oracle (PwshOracleTests) independently validates every input's validity.
/// </summary>
internal static class CorpusManifest
{
    private static ManifestEntry E(string slug, string input, string notes) =>
        new(slug, input, notes, false, ManifestTransform.None);

    private static ManifestEntry EI(string slug, string input, string notes) =>
        new(
            slug,
            input,
            notes,
            false,
            ManifestTransform.None,
            PowerShellInitialStateMode:
                PwshInitialStateMode.IsolatedNonInteractiveNoProfile);

    private static ManifestEntry W(
        string slug,
        string input,
        string notes,
        bool outOfScope = false) =>
        new(
            slug,
            input,
            notes,
            outOfScope,
            ManifestTransform.None,
            IncludeElements: true,
            IncludeStructure: true,
            IncludeOptionalAssertions: true,
            IncludeV03Assertions: true,
            PowerShellDialect: PwshDialect.WindowsPowerShell51);

    private static ManifestEntry P(string slug, string input, string notes) =>
        new(slug, input, notes, false, ManifestTransform.None, IncludeElements: true);

    private static ManifestEntry S(string slug, string input, string notes) =>
        new(slug, input, notes, false, ManifestTransform.None, IncludeStructure: true);

    private static ManifestEntry SI(string slug, string input, string notes) =>
        new(
            slug,
            input,
            notes,
            false,
            ManifestTransform.None,
            IncludeStructure: true,
            PowerShellInitialStateMode:
                PwshInitialStateMode.IsolatedNonInteractiveNoProfile);

    private static ManifestEntry V(string slug, string input, string notes) =>
        new(
            slug,
            input,
            notes,
            false,
            ManifestTransform.None,
            IncludeStructure: true,
            IncludeV03Assertions: true);

    private static ManifestEntry VI(string slug, string input, string notes) =>
        new(
            slug,
            input,
            notes,
            false,
            ManifestTransform.None,
            IncludeStructure: true,
            IncludeV03Assertions: true,
            PowerShellInitialStateMode:
                PwshInitialStateMode.IsolatedNonInteractiveNoProfile);

    private static ManifestEntry VIE(string slug, string input, string notes) =>
        new(
            slug,
            input,
            notes,
            false,
            ManifestTransform.None,
            IncludeElements: true,
            IncludeStructure: true,
            IncludeV03Assertions: true,
            PowerShellInitialStateMode:
                PwshInitialStateMode.IsolatedNonInteractiveNoProfile);

    private static ManifestEntry VE(string slug, string input, string notes) =>
        new(
            slug,
            input,
            notes,
            false,
            ManifestTransform.None,
            IncludeElements: true,
            IncludeStructure: true,
            IncludeV03Assertions: true);

    private static ManifestEntry A(string slug, string name, string input, string notes) =>
        new(
            slug,
            input,
            notes,
            false,
            ManifestTransform.None,
            IncludeOptionalAssertions: true,
            DisplayName: name);

    private static ManifestEntry Oos(string slug, string input, string notes) =>
        new(slug, input, notes, true, ManifestTransform.None);

    private static ManifestEntry OosI(string slug, string input, string notes) =>
        new(
            slug,
            input,
            notes,
            true,
            ManifestTransform.None,
            PowerShellInitialStateMode:
                PwshInitialStateMode.IsolatedNonInteractiveNoProfile);

    private static ManifestEntry Enc(string slug, string decoded, string notes, bool oos = false) =>
        new(slug, decoded, notes, oos, ManifestTransform.EncodeCommand);

    private static ManifestEntry Big(string slug, string prefix, string notes) =>
        new(slug, prefix, notes, true, ManifestTransform.OversizedInput);

    private static string B64(string s) =>
        Convert.ToBase64String(Encoding.Unicode.GetBytes(s));

    private static string NestIex(string inner, int depth)
    {
        for (var i = 0; i < depth; i++)
        {
            inner = "iex '" + inner.Replace("'", "''") + "'";
        }

        return inner;
    }

    internal static IReadOnlyList<ManifestEntry> All() => new List<ManifestEntry>
    {
        // ---- Simple cmdlet (§13: ≥10) ----
        S("simple_get_date", "Get-Date", "Bare cmdlet, no args."),
        E("simple_get_childitem", "Get-ChildItem", "Bare cmdlet, no args."),
        E("simple_get_location", "Get-Location", "Bare cmdlet, no args."),
        E("simple_get_process", "Get-Process", "Bare cmdlet, no args."),
        E("simple_get_command", "Get-Command", "Bare cmdlet, no args."),
        E("simple_get_content_path", "Get-Content C:\\logs\\app.log",
            "Cmdlet with one positional path."),
        E("simple_get_item_path", "Get-Item C:\\Users\\user\\file.txt",
            "Cmdlet with a drive-qualified positional path."),
        E("simple_test_path", "Test-Path C:\\temp",
            "Test-Path FileVerb with one positional path."),
        E("simple_get_filehash", "Get-FileHash C:\\downloads\\setup.exe",
            "Get-FileHash FileVerb with one positional path."),
        E("simple_write_output", "Write-Output hello",
            "Write-Output with a non-path literal arg."),
        E("simple_resolve_path", "Resolve-Path .\\rel\\sub",
            "Resolve-Path with a relative positional path."),
        E("simple_get_member", "Get-Member", "Bare non-file cmdlet."),

        // ---- Alias resolution (§13: ≥15) — assert raw Tokens + CanonicalVerb ----
        E("alias_gci", "gci C:\\logs", "gci resolves to Get-ChildItem."),
        E("alias_ls", "ls C:\\logs", "ls resolves to Get-ChildItem."),
        E("alias_dir", "dir C:\\logs", "dir resolves to Get-ChildItem."),
        E("alias_rm", "rm C:\\temp\\old.txt", "rm resolves to Remove-Item."),
        E("alias_del", "del C:\\temp\\old.txt", "del resolves to Remove-Item."),
        E("alias_ri", "ri C:\\temp\\old.txt", "ri resolves to Remove-Item."),
        E("alias_cat", "cat C:\\logs\\app.log", "cat resolves to Get-Content."),
        E("alias_type", "type C:\\logs\\app.log", "type resolves to Get-Content."),
        E("alias_cp", "cp src.txt dst.txt", "cp resolves to Copy-Item."),
        E("alias_mv", "mv old.txt new.txt", "mv resolves to Move-Item."),
        E("alias_ni", "ni C:\\temp\\new.txt", "ni resolves to New-Item."),
        E("alias_mkdir", "mkdir C:\\temp\\newdir", "mkdir resolves to New-Item."),
        E("alias_sl", "sl C:\\repo", "sl resolves to Set-Location."),
        E("alias_echo", "echo hello", "echo resolves to Write-Output."),
        E("alias_sls", "sls error C:\\logs\\app.log", "sls resolves to Select-String."),
        E("alias_gc", "gc C:\\logs\\app.log", "gc resolves to Get-Content."),
        E("alias_gi", "gi C:\\temp\\f.txt", "gi resolves to Get-Item."),
        E("alias_select", "select Name", "select resolves to Select-Object."),

        // ---- Native command / multi-token chain (§13: ≥10) ----
        E("native_git_status", "git status", "Native git, two-token chain."),
        E("native_git_push", "git push origin main",
            "Greedy verb-chain walk absorbs origin and main."),
        E("native_dotnet_build", "dotnet build", "Native dotnet, two-token chain."),
        E("native_dotnet_ef", "dotnet ef migrations add InitialCreate",
            "Chain stops at the capitalized InitialCreate token."),
        E("native_npm_install", "npm install", "Native npm, two-token chain."),
        E("native_kubectl_get", "kubectl get pods", "Native kubectl, three-token chain."),
        E("native_docker_compose", "docker compose up", "Native docker, three-token chain."),
        E("native_python_script", "python script.py",
            "Native python with a script-file positional."),
        E("native_git_c_flag", "git -C C:\\repo status",
            "git -C consumes a directory path (shared bash flag table)."),
        E("native_git_commit", "git commit -m \"initial\"",
            "git commit; -m is not a flag-with-value so the chain stops."),
        E("native_xcopy", "xcopy C:\\src C:\\dst",
            "xcopy native file utility — one-token chain, positionals are paths."),
        E("native_where", "where git",
            "where is never aliased (§6.3 rule 3); parses as a native command."),

        // ---- Pipeline (§13: ≥15) ----
        EI("pipeline_gci_rm", "gci | rm", "Two-clause alias pipeline."),
        EI("pipeline_process_stop", "Get-Process | Stop-Process", "Cmdlet pipeline."),
        EI("pipeline_filter_remove", "gci | ? { $_.Length -gt 1mb } | rm",
            "Three-clause pipeline with an opaque script-block filter."),
        EI("pipeline_select", "Get-ChildItem | Select-Object Name", "Pipeline into Select-Object."),
        EI("pipeline_selectstring", "Get-Content app.log | Select-String error",
            "Pipeline into Select-String."),
        EI("pipeline_sort", "gci | Sort-Object Length", "Pipeline into Sort-Object."),
        EI("pipeline_measure", "gci | measure", "Pipeline into the measure alias."),
        EI("pipeline_where_block", "Get-Process | Where-Object { $_.CPU -gt 10 }",
            "Where-Object with an opaque script block."),
        EI("pipeline_gci_path_remove", "gci C:\\logs | Remove-Item",
            "First clause carries a path; piped to Remove-Item."),
        EI("pipeline_foreach_alias", "Get-ChildItem | foreach { $_ }",
            "foreach after a pipe is the ForEach-Object alias, not the loop keyword."),
        EI("pipeline_percent_block", "gci | % { Remove-Item $_ }",
            "% resolves to ForEach-Object; its unknown execution region keeps the body command visible."),
        EI("pipeline_ps_sort", "ps | sort CPU", "Two aliases piped."),
        EI("pipeline_four_stage", "gci -Recurse C:\\logs | ? Name | sort | rm",
            "Four-stage pipeline mixing flags, opaque, and aliases."),
        EI("pipeline_dir_gc", "dir | gc", "dir piped into gc — both aliases."),
        EI("pipeline_out_file", "Get-Process | Out-File C:\\out\\procs.txt",
            "Pipeline terminating in Out-File with a path."),
        EI("pipeline_format_table", "Get-Service | ft", "Pipeline into the ft alias."),
        EI("pipeline_select_then_rm", "gci C:\\tmp | Select-Object -First 5 | rm",
            "Pipeline with a value-binding parameter mid-chain."),

        // ---- Compound / statement separator (§13: ≥10) ----
        E("compound_semicolon", "Get-Date; Get-Location", "Two statements joined by ;."),
        E("compound_andif", "Test-Path C:\\x && Get-ChildItem C:\\x",
            "&& pipeline-chain operator (PowerShell 7)."),
        E("compound_orif", "Test-Path C:\\x || New-Item C:\\x",
            "|| pipeline-chain operator (PowerShell 7)."),
        E("compound_three_semicolon", "gci; rm a.txt; rm b.txt", "Three ;-joined statements."),
        E("compound_mixed_operators", "Get-Date && Get-Location || Get-Process",
            "Mixed && / || chain."),
        E("compound_group", "(Get-ChildItem)", "A parenthesized pipeline marks IsSubshell."),
        SI("compound_group_pipeline", "(gci C:\\tmp | Remove-Item)",
            "A group wrapping a pipeline; both clauses marked IsSubshell."),
        E("compound_newline", "Get-Date\nGet-Location",
            "A bare newline is a statement separator."),
        E("compound_andif_then_semicolon", "gci && rm a.txt; Get-Date",
            "&& then ; in one compound."),
        E("compound_group_then_clause", "(gci) ; Get-Date",
            "A group followed by a ;-joined clause."),
        EI("compound_pipe_newline", "gci |\nrm",
            "A newline right after | collapses; the pipeline continues."),
        E("compound_continuation", "Get-ChildItem `\n  C:\\logs",
            "A backtick line continuation joins two physical lines."),

        // ---- Set-Location propagation (§13: ≥10) ----
        E("setloc_cd_then_git", "cd C:\\repo && git status",
            "cd attributes C:/repo to the subsequent clause."),
        E("setloc_setlocation_then_gci", "Set-Location C:\\src && Get-ChildItem",
            "Set-Location attribution to the next clause."),
        E("setloc_two_cd", "cd C:\\a && cd C:\\b && gci",
            "A later Set-Location replaces the attributed cwd."),
        E("setloc_dynamic_target", "cd $repo; gci",
            "A dynamic cd target yields dynamic attribution."),
        E("setloc_dash", "cd -; gci",
            "Set-Location - (previous location) is not statically knowable."),
        E("setloc_path_param", "Set-Location -Path C:\\proj && rm temp.txt",
            "Set-Location target taken from -Path."),
        E("setloc_through_group", "(cd C:\\sensitive) && Remove-Item *",
            "Attribution propagates through a group — ( ) is not a subshell."),
        E("setloc_tilde", "cd ~ && gci",
            "cd ~ attributes the home directory."),
        E("setloc_no_arg", "Set-Location && gci",
            "Set-Location with no target attributes the home directory."),
        E("setloc_relative_after_literal", "cd C:\\repo && cd sub && gci",
            "A relative cd resolves under the prior attributed cwd."),
        E("setloc_non_fs_drive", "cd HKLM:; gci",
            "cd to a non-FileSystem PSDrive yields dynamic attribution."),
        E("setloc_pushd_no_attribution", "pushd C:\\stack; gci",
            "Push-Location is a CwdVerb but adds no attribution arg (§9)."),
        E("setloc_andif", "cd C:\\repo && git status",
            "Attribution propagates across the && operator."),

        // ---- Quote handling (§13: ≥10) ----
        E("quote_single_literal", "echo 'literal $HOME'",
            "Single quotes preserve $HOME literally — no expansion."),
        E("quote_double_var", "echo \"value is $env:TEMP\"",
            "Double quotes keep $env:TEMP literal in the token value."),
        E("quote_single_path", "Get-Content 'C:\\logs\\app.log'",
            "A single-quoted path still resolves."),
        E("quote_double_spaces", "Copy-Item \"C:\\my files\\doc.txt\" \"C:\\backup\"",
            "Double-quoted paths with embedded spaces."),
        E("quote_backtick_escape", "Write-Output \"a`tb\"",
            "Backtick escape inside a double-quoted string."),
        E("quote_doubled_single", "echo 'it''s here'",
            "A doubled '' is an escaped single quote."),
        E("quote_doubled_double", "echo \"say \"\"hello\"\"\"",
            "A doubled \"\" is an escaped double quote."),
        E("quote_herestring_expandable", "Get-Content @\"\nC:\\logs\\app.log\n\"@",
            "An expandable here-string argument."),
        E("quote_herestring_literal", "Write-Output @'\n$literal text\n'@",
            "A literal here-string preserves $literal."),
        E("quote_path_with_spaces", "Get-Item \"C:\\path with spaces\\file.txt\"",
            "A double-quoted drive path with spaces."),
        E("quote_single_quoted_command", "& 'C:\\Program Files\\app\\tool.exe' run",
            "A single-quoted command name invoked with the call operator."),
        E("quote_empty_double", "Write-Output \"\"", "An empty double-quoted string."),

        // ---- Parameter binding (§13: ≥25) ----
        E("bind_path_recurse", "Get-ChildItem -Path C:\\logs -Recurse",
            "Named -Path plus the -Recurse switch."),
        E("bind_recurse_positional", "Get-ChildItem -Recurse C:\\logs",
            "-Recurse is a switch; C:\\logs stays a positional path."),
        E("bind_depth_value", "Get-ChildItem -Depth 3 C:\\logs",
            "-Depth is value-binding; 3 is its value, C:\\logs the positional."),
        E("bind_switch_positional_interleave", "Copy-Item -Force a.txt -Verbose b.txt",
            "Switches do not advance the positional index (§6.5.1)."),
        E("bind_source_destination", "Copy-Item -Path src.txt -Destination dst.txt",
            "Two path-typed parameters."),
        E("bind_literalpath", "Get-Content -LiteralPath C:\\logs\\app.log",
            "-LiteralPath value is a path."),
        E("bind_remove_recurse_force", "Remove-Item -Path C:\\temp -Recurse -Force",
            "Named path plus two trailing switches."),
        E("bind_setcontent_value", "Set-Content -Path out.txt -Value hello",
            "-Path value is a path; -Value content is not."),
        E("bind_colon_path", "Get-ChildItem -Path:C:\\logs",
            "Colon-form parameter binds its value (§6.5.3 rule 1)."),
        E("bind_colon_switch", "Get-ChildItem -Recurse:$true C:\\logs",
            "Colon-form on a switch parameter."),
        E("bind_newitem_itemtype", "New-Item -Path C:\\temp\\f.txt -ItemType File",
            "-ItemType value is a literal, not a path."),
        E("bind_filter_glob", "Get-ChildItem -Filter *.log C:\\logs",
            "-Filter value is a glob slot; C:\\logs is the positional path."),
        E("bind_selectstring_pattern", "Select-String -Pattern error -Path app.log",
            "-Pattern is not a path; -Path is."),
        E("bind_encoding", "Get-Content -Encoding UTF8 C:\\x.txt",
            "-Encoding is value-binding but its value is not a path."),
        E("bind_erroraction", "Get-ChildItem -ErrorAction SilentlyContinue C:\\logs",
            "A value-bearing common parameter."),
        E("bind_prefix_literalpath", "Get-ChildItem -lp C:\\logs",
            "-lp prefix-matches -LiteralPath (§6.5.2)."),
        E("bind_prefix_recurse", "Get-ChildItem -rec C:\\logs",
            "-rec prefix-matches the -Recurse switch."),
        E("bind_whatif_switch", "Remove-Item -WhatIf C:\\temp\\x.txt",
            "-WhatIf common switch."),
        E("bind_two_positionals", "Get-ChildItem C:\\a C:\\b",
            "Two positional paths."),
        E("bind_outfile_filepath", "Out-File -FilePath C:\\out.txt",
            "-FilePath value is a path."),
        E("bind_force_hidden", "Get-ChildItem -Force -Hidden C:\\x",
            "Two switches then a positional path."),
        E("bind_testpath_pathtype", "Test-Path -Path C:\\x -PathType Leaf",
            "-PathType value is a literal, not a path."),
        E("bind_unknown_param", "Get-ChildItem -Whatever C:\\logs",
            "An unknown parameter defaults to a switch; the positional survives."),
        E("bind_newitem_directory", "New-Item -ItemType Directory -Path C:\\newdir",
            "-Path positional path; -ItemType literal."),
        E("bind_destination_first", "Copy-Item -Destination C:\\dst -Path C:\\src",
            "Named parameters in either order."),
        E("bind_include_exclude", "Get-ChildItem -Include *.txt -Exclude *.tmp C:\\x",
            "-Include / -Exclude are glob slots."),
        E("bind_rename_newname", "Rename-Item -Path old.txt -NewName new.txt",
            "Rename-Item named parameters."),
        E("bind_gci_file_switch", "Get-ChildItem -File C:\\logs",
            "-File is a switch on Get-ChildItem (§6.5.4 collision)."),
        E("bind_importcsv_delimiter", "Import-Csv -Path data.csv -Delimiter \";\"",
            "-Delimiter is value-binding but not a path."),
        E("bind_splat", "Copy-Item @itemArgs",
            "A splat argument is opaque DynamicSkip."),
        E("bind_name_newitem", "New-Item -Name report.txt -Path C:\\out",
            "-Name is a path leaf for New-Item (§7.1)."),

        // ---- Redirect (§13: ≥10) ----
        V("redirect_out", "Get-Date > out.txt", "> stdout redirect (truncate)."),
        V("redirect_append", "Get-Date >> log.txt", ">> stdout append."),
        V("redirect_err", "Get-Process 2> err.txt", "2> stderr redirect."),
        V("redirect_err_append", "Get-Process 2>> err.txt", "2>> stderr append."),
        V("redirect_verbose", "Get-Date 3> verbose.txt", "3> verbose stream — maps lossily to Out."),
        V("redirect_warning", "Get-Date 4> warn.txt", "4> warning stream — maps lossily to Out."),
        V("redirect_debug", "Get-Date 5> debug.txt", "5> debug stream — maps lossily to Out."),
        V("redirect_information", "Get-Date 6> info.txt", "6> information stream — maps lossily to Out."),
        V("redirect_all", "Get-Date *> all.txt", "*> all-streams redirect — maps lossily to Out."),
        V("redirect_all_append", "Get-Date *>> all.txt", "*>> all-streams append."),
        V("redirect_merge_2to1", "Get-Process 2>&1", "2>&1 stream merge — target carries &1."),
        V("redirect_merge_3to1", "Get-Date 3>&1", "3>&1 stream merge."),
        V("redirect_null", "Get-Date > $null", "$null remains explicit but incomplete until the public model represents the discard sink."),

        // ---- pwsh -Command / -EncodedCommand recursion (§13: ≥15) ----
        E("recursion_command_quoted", "pwsh -Command \"Remove-Item C:\\tmp\\x\"",
            "pwsh -Command with a quoted-string payload; inner clause surfaces wrapped."),
        E("recursion_short_c", "pwsh -c \"Get-Date\"",
            "The short -c flag is recognized as -Command."),
        E("recursion_command_pipeline", "pwsh -Command \"gci | rm\"",
            "A static -Command child pipeline retains both authored stages."),
        E("recursion_command_scriptblock", "pwsh -Command { Get-Date }",
            "pwsh -Command with a script-block payload."),
        E("recursion_command_bare", "pwsh -Command Remove-Item C:\\tmp\\x",
            "The bare/multi-token -Command form."),
        E("recursion_powershell_host", "powershell -Command \"Get-Process\"",
            "The powershell host name is also recognized."),
        E("recursion_command_noprofile", "pwsh -NoProfile -Command \"Get-Date\"",
            "A switch before -Command does not block recursion."),
        E("recursion_command_setlocation", "pwsh -Command \"cd C:\\x && gci\"",
            "Set-Location attribution works inside a recursed command."),
        E("recursion_command_nested", "pwsh -Command { pwsh -Command { Get-Date } }",
            "Two-level -Command recursion."),
        Enc("recursion_encoded_getdate", "Get-Date",
            "-EncodedCommand decodes base64/UTF-16LE to Get-Date."),
        Enc("recursion_encoded_remove", "Remove-Item C:\\tmp\\x",
            "-EncodedCommand decoding to a Remove-Item clause."),
        Enc("recursion_encoded_pipeline", "Get-Process | Stop-Process",
            "A static decoded child pipeline retains both authored stages."),
        Enc("recursion_encoded_controlflow", "if ($true) { Get-Date }",
            "An -EncodedCommand payload that decodes to control flow — inner unparseable propagates.", oos: true),
        E("recursion_encoded_nested", "pwsh -EncodedCommand " + B64("Get-Date"),
            "An -EncodedCommand payload that is itself a pwsh -EncodedCommand invocation."),
        Oos("recursion_encoded_bad_base64", "pwsh -EncodedCommand ###not-base64###",
            "A malformed base64 -EncodedCommand payload — the outer pwsh invocation still parses."),
        E("recursion_file_not_recursed", "pwsh -File C:\\scripts\\deploy.ps1",
            "pwsh -File is not recursion; the script path is an ordinary path arg."),
        E("recursion_iex_static", "iex \"Remove-Item C:\\x\"",
            "A static iex payload surfaces its inner Remove-Item clause (§10)."),
        Oos("recursion_depth_overflow",
            "pwsh -Command { pwsh -Command { pwsh -Command { pwsh -Command { pwsh -Command { pwsh -Command { Get-Date } } } } } }",
            "Six nested -Command levels exceed the depth-5 cap."),

        // ---- Dynamic skip (§13: ≥10) ----
        E("dynamic_call_variable", "& $exe arg1",
            "The call operator on a variable — VerbChain.IsDynamic is set."),
        E("dynamic_call_variable_noargs", "& $tool",
            "A bare dynamic call with no args."),
        E("dynamic_variable_command", "$cmd",
            "A bare variable at statement position is a dynamic command name."),
        V("dynamic_call_scriptblock", "& { Get-Date }",
            "The direct call operator is a typed synchronous child-scope region and exposes its body without a synthetic host clause."),
        E("dynamic_env_path_arg", "Get-Content $env:TEMP\\session.log",
            "An $env: reference in a path slot resolves to DynamicSkip."),
        E("dynamic_variable_path_arg", "Remove-Item $targetPath",
            "A $var in a path slot is DynamicSkip."),
        S("dynamic_subexpression_arg", "Get-Content $(Get-Location)",
            "A $( ) subexpression argument is opaque DynamicSkip."),
        E("dynamic_array_subexpression", "Write-Output @(1, 2, 3)",
            "An @( ) array subexpression argument is opaque DynamicSkip."),
        E("dynamic_glob_arg", "Get-ChildItem C:\\logs\\*.log",
            "A glob in a path slot — Kind=Glob, IsPath=true."),
        E("dynamic_comma_array", "Remove-Item a.txt,b.txt",
            "A comma-array path token is marked DynamicSkip (§8)."),
        E("dynamic_scriptblock_arg", "ForEach-Object { $_.Name }",
            "A script-block argument to ForEach-Object."),
        E("dynamic_hash_literal", "New-Item -Path C:\\x @{ Force = $true }",
            "A hash literal argument is opaque DynamicSkip."),
        E("dynamic_stop_parsing", "git --% log --oneline | findstr x",
            "The --% stop-parsing token swallows the line remainder."),

        // ---- Per-verb / per-parameter path rules (§13: ≥10) ----
        E("pathrule_copy_two_paths", "Copy-Item src.txt dst.txt",
            "Copy-Item positional 0 = source path, positional 1 = destination path."),
        E("pathrule_move_two_paths", "Move-Item old.txt archive\\old.txt",
            "Move-Item positionals are both paths."),
        E("pathrule_rename", "Rename-Item report.txt report-final.txt",
            "Rename-Item positional 0 = path, positional 1 = new name."),
        E("pathrule_selectstring_positional", "Select-String error app.log",
            "Select-String positional 0 = pattern, positional 1 = path."),
        E("pathrule_newitem_positional", "New-Item C:\\temp\\created",
            "New-Item positional 0 = path."),
        E("pathrule_setcontent_positional", "Set-Content notes.txt",
            "Set-Content positional 0 = path."),
        E("pathrule_addcontent", "Add-Content log.txt entry",
            "Add-Content positional 0 = path; the rest is content."),
        E("pathrule_registry_not_path", "Remove-Item HKLM:\\Software\\Vendor",
            "A registry-provider path is not a filesystem path (§8 step 4)."),
        E("pathrule_curl_url", "curl -o C:\\out.txt https://example.com/file",
            "Native curl: -o value is a path; the positional URL is not."),
        E("pathrule_provider_qualifier", "Get-Content FileSystem::C:\\logs\\app.log",
            "A FileSystem:: provider qualifier is stripped before resolution."),
        E("pathrule_unc_path", "Get-ChildItem \\\\internal-host.example\\share\\data",
            "A UNC path is rooted and normalized."),
        E("pathrule_home_variable", "Get-Content $HOME\\notes.txt",
            "$HOME expands to the configured home directory."),

        // ---- Unparseable: control flow, definitions, blocks, etc. (§13: ≥20) ----
        Oos("unparseable_if", "if ($true) { Get-Date }",
            "An if statement — valid PowerShell the parser declines to model."),
        Oos("unparseable_foreach", "foreach ($f in 1, 2, 3) { Write-Output $f }",
            "A foreach loop (keyword followed by '(')."),
        Oos("unparseable_while", "while ($false) { Get-Date }",
            "A while loop."),
        Oos("unparseable_for", "for ($i = 0; $i -lt 3; $i++) { Get-Date }",
            "A for loop."),
        Oos("unparseable_switch", "switch (1) { 1 { 'one' } }",
            "A switch statement."),
        Oos("unparseable_dowhile", "do { Get-Date } while ($false)",
            "A do/while loop."),
        Oos("unparseable_function", "function Show-Thing { Get-Date }",
            "A function definition."),
        Oos("unparseable_class", "class Widget { }",
            "A class definition."),
        Oos("unparseable_assignment", "$result = Get-Date",
            "An assignment statement."),
        Oos("unparseable_env_assignment", "$env:EDITOR = 'code'",
            "An $env: assignment statement."),
        Oos("unparseable_return", "return 0",
            "A return statement."),
        Oos("unparseable_throw", "throw 'boom'",
            "A throw statement."),
        Oos("unparseable_exit", "exit 0",
            "An exit statement."),
        Oos("unparseable_break", "break",
            "A bare break statement."),
        Oos("unparseable_type_literal", "[System.Math]::Sqrt(2)",
            "A bare type-literal / .NET method-call statement."),
        Oos("unparseable_trailing_amp", "git status &",
            "A trailing & background-job operator."),
        Oos("unparseable_try_catch", "try { Get-Date } catch { }",
            "A try/catch block."),
        Oos("unparseable_trap", "trap { 'caught' }",
            "A trap statement."),
        Oos("unparseable_param_block", "param($Name)",
            "A param() block."),
        Big("unparseable_oversized", "Get-ChildItem ",
            "Input over the 64 KiB parser cap — real pwsh still parses the outer command."),
        E("unparseable_unbalanced_single_quote", "Get-Content 'unbalanced",
            "An unbalanced single quote — a genuine syntax error."),
        E("unparseable_unbalanced_double_quote", "Write-Output \"unclosed",
            "An unbalanced double quote."),
        E("unparseable_stray_brace", "Get-ChildItem }",
            "A stray closing brace."),
        E("unparseable_unbalanced_paren", "Get-ChildItem )",
            "A stray closing parenthesis."),
        E("unparseable_unclosed_scriptblock", "gci | ? { $_.Name",
            "An unterminated script block."),
        E("unparseable_unterminated_block_comment", "Get-Date <# never closed",
            "An unterminated block comment."),
        E("unparseable_unclosed_subexpression", "Get-Content $(Get-Location",
            "An unterminated $( ) subexpression."),
        E("unparseable_unterminated_herestring", "Write-Output @\"\nnever closed",
            "An unterminated here-string."),

        // ---- Issue #52: hyphenated parameters and native inline values ----
        E("native_git_worktree_equals", "git --work-tree=../test add somefile",
            "Issue #52: native --flag=value stays atomic, then splits into flag and path value."),
        E("native_git_worktree_spaced", "git --work-tree repo status",
            "Issue #52: a hyphenated curated flag consumes and path-classifies its spaced value."),
        E("native_colon_option", "git --option:value status",
            "Native colon options are preserved verbatim; colon binding is cmdlet-only."),
        E("bind_hyphenated_colon", "Get-Thing -Name-Part:value",
            "A hyphenated cmdlet parameter remains one token and retains colon binding."),
        E("bind_equals_not_cmdlet_binding", "Get-Item -Path=foo bar",
            "Equals does not bind a cmdlet parameter value; the following positional remains a path."),
        E("bind_equals_colon_value_is_dynamic", "Remove-Item -Path=C:\\Windows",
            "PowerShell reads this as parameter '-Path=C:' plus argument '\\Windows' — a name that "
            + "can never bind, so the value safe-fails to DynamicSkip."),
        E("bind_question_mark_help", "Get-Help -?",
            "'-?' is a single parameter token, not a bare dash plus a '?' glob."),

        // ---- Issue #64: path-shaped operands after native verb chains ----
        E("native_kubectl_apply_yaml", "kubectl apply deployment.yaml",
            "A real non-Git CLI exposes a lowercase YAML file without a command-specific rule."),

        // ---- Issue #63: Invoke-Expression command-string recursion ----
        E("iex_full_name_static", "Invoke-Expression 'Get-Date'",
            "The full cmdlet name recurses into one static literal payload."),
        E("iex_command_parameter_static", "Invoke-Expression -Command 'Get-Process'",
            "The exact -Command parameter binds one static payload."),
        S("iex_variable_dynamic", "Invoke-Expression $code",
            "A variable payload remains an Invoke-Expression clause with one DynamicSkip arg."),
        E("iex_interpolated_dynamic", "iex \"Remove-$noun C:\\x\"",
            "An interpolated payload remains opaque and dynamic."),
        E("iex_concatenated_dynamic", "iex ('Get-' + 'Date')",
            "Literal concatenation is not evaluated and collapses to one DynamicSkip arg."),
        Oos("iex_pipeline_dynamic", "Get-Content script.ps1 | Invoke-Expression",
            "Pipeline-fed expression code is valid PowerShell but safe-fails as unparseable."),
        E("iex_inherits_location", "Set-Location C:\\a && iex 'Remove-Item child.txt'",
            "A static payload inherits the caller's effective location."),
        E("iex_exports_location", "iex 'Set-Location C:\\b' && Remove-Item child.txt",
            "A location change inside iex affects following outer clauses."),
        Oos("iex_recursion_depth_overflow", NestIex("Get-Date", 6),
            "Six nested static expression strings exceed the shared depth-five cap."),
        E("iex_quoted_alias_dynamic", "& 'iex' $code",
            "A quoted alias invoked through the call operator still safe-fails its payload."),
        E("iex_module_qualified_dynamic", "Microsoft.PowerShell.Utility\\Invoke-Expression $code",
            "A module-qualified cmdlet name still receives expression security handling."),
        E("iex_unicode_interpolation_dynamic", "iex \"Remove-$é C:\\x\"",
            "Unicode variable interpolation cannot hide a clean inner verb."),
        E("iex_comma_array_dynamic", "Invoke-Expression Write-Output,OTHER",
            "An unquoted comma array is computed rather than one static scalar string."),
        E("iex_dynamic_location", "Set-Location C:\\safe && iex $code; Remove-Item child.txt",
            "Dynamic current-scope code invalidates location attribution for following paths."),
        E("dynamic_interpolated_iex_name", "& \"i$part\" $code",
            "An interpolated call-operator command name is dynamic and cannot bypass iex handling."),
        E("iex_unicode_escaped_alias", "& \"i`u{65}x\" $code",
            "A Unicode-escaped iex name is decoded before command identity checks."),
        E("iex_bare_backtick_newline", "iex Write-Output` harmless`nGet-Date",
            "A backtick newline escape in a bare static payload surfaces both commands."),
        E("iex_herestring_backtick_newline", "iex @\"\nWrite-Output ok`nGet-Date\n\"@",
            "An expandable here-string decodes its backtick newline before recursion."),
        E("iex_backtick_location", "Set-Location C:\\safe && iex Write-Output` ok`nSet-Location` C:\\evil && Remove-Item child.txt",
            "A hidden escaped-newline location change is surfaced and propagated."),
        E("iex_command_colon_inline", "iex -Command:Get-Date",
            "The exact colon-form -Command parameter binds an inline static payload."),
        E("iex_command_colon_quoted", "iex -Command:'Get-Date'",
            "An empty colon-form parameter tail binds the following quoted payload."),
        E("iex_command_colon_dynamic", "iex -Command:$code",
            "A dynamic inline colon-form payload remains one DynamicSkip arg."),
        E("iex_vertical_tab_path", "iex \"Remove-Item`vC:\\x\"",
            "Decoded vertical-tab whitespace separates the inner path argument."),
        E("iex_form_feed_path", "iex \"Remove-Item`fC:\\x\"",
            "Decoded form-feed whitespace separates the inner path argument."),
        E("iex_unicode_whitespace_path", "iex \"Remove-Item`u{2003}C:\\x\"",
            "Decoded Unicode whitespace separates the inner path argument."),
        E("iex_vertical_tab_location", "Set-Location C:\\safe && iex \"Set-Location`vC:\\evil\" && Remove-Item child.txt",
            "Decoded vertical-tab whitespace preserves an inner location change."),
        E("iex_command_colon_comment", "iex -Command:#comment",
            "A comment after an empty colon value leaves -Command without a payload."),
        E("iex_command_colon_backtick_newline", "iex -Command:Write-Output`nGet-Date",
            "An inline colon payload decodes backtick newline before recursion."),
        Oos("iex_decoded_nul", "iex \"Remove-Item`0C:\\x\"",
            "A decoded NUL safe-fails instead of merging a hidden path into the verb."),
        E("iex_command_colon_unicode_escape", "iex -Command:Get-`u{44}ate",
            "An inline colon payload consumes and decodes a complete Unicode escape."),
        Oos("iex_dot_invocation", ". iex 'Remove-Item C:\\x'",
            "Dot invocation is valid PowerShell but outside the parser grammar and safe-fails."),
        E("iex_scoped_interpolation_dynamic", "iex \"Remove-$:noun C:\\x\"",
            "Scoped interpolation syntax keeps the expression payload dynamic."),
        Oos("iex_module_qualified_remove", "iex 'Microsoft.PowerShell.Management\\Remove-Item C:\\x'",
            "An unsupported module-qualified inner cmdlet safe-fails instead of hiding its identity."),
        Oos("iex_module_qualified_location", "Set-Location C:\\safe; iex 'Microsoft.PowerShell.Management\\Set-Location C:\\evil'; Remove-Item child.txt",
            "An unsupported module-qualified location mutation safe-fails instead of preserving stale cwd."),
        E("dynamic_command_location", "Set-Location C:\\safe && & \"i$part\" $code; Get-Item child.txt",
            "Any dynamic command invalidates following current-scope location attribution."),
        E("quoted_expression_command", "\"iex\" 'Get-Date'",
            "A quoted expression without the call operator is not a command invocation."),
        Oos("iex_quoted_inner_expression", "Set-Location C:\\safe; iex '\"Set-Location\" C:\\evil'; Get-Item child.txt",
            "A quoted inner expression is valid outer syntax but not a supported command invocation."),
        E("iex_escape_character", "Set-Location C:\\safe && iex \"S`et-Location C:\\evil\"; Get-Item child.txt",
            "The backtick e escape becomes ESC and cannot spoof Set-Location."),
        E("iex_invalid_unicode_empty", "iex \"Get-`u{}Date\"",
            "An empty Unicode escape is a PowerShell syntax error."),
        E("iex_invalid_unicode_range", "iex \"Get-`u{110000}Date\"",
            "An out-of-range Unicode escape is a PowerShell syntax error."),
        E("iex_invalid_unicode_colon", "iex -Command:Get-`u{}Date",
            "Malformed Unicode syntax in an inline colon payload safe-fails."),
        Oos("iex_quoted_module_remove", "iex \"& 'Microsoft.PowerShell.Management\\Remove-Item' C:\\x\"",
            "A quoted module-qualified inner cmdlet safe-fails under the call operator."),
        Oos("iex_quoted_module_location", "Set-Location C:\\safe; iex \"& 'Microsoft.PowerShell.Management\\Set-Location' C:\\evil\"; Remove-Item child.txt",
            "A quoted module-qualified location mutation cannot preserve stale cwd."),

        // ---- Issue #62: authored option placement and heuristic boundaries ----
        P("git_global_option_provenance", "git -C C:\\repo commit",
            "Issue #62: global -C and its path occur before the commit element."),
        P("git_subcommand_option_provenance", "git commit -C HEAD~1",
            "Issue #62: command-scoped -C occurs after the parser-classified commit verb."),
        P("git_global_config_provenance", "git -c user.name=Jane commit",
            "Issue #62: lowercase -c consumes a non-path configuration value."),
        P("git_subcommand_config_provenance", "git commit -c HEAD~1",
            "Issue #62: lowercase command-scoped -c preserves its post-commit position."),
        P("git_mixed_option_provenance", "git -C C:\\repo commit -C HEAD~1",
            "Issue #62: both global and command-scoped -C occurrences remain distinct."),
        P("git_heuristic_boundary_provenance", "git --no-pager commit -C HEAD~1",
            "Issue #62: authored order survives when a valueless option stops the greedy verb walk."),

        // ---- Issue #62 adversarial follow-up: native option case collisions ----
        P("wget_case_distinct_output_options",
            "wget -o wget.log -O download.bin https://example.invalid/file",
            "Wget -o writes a log file while -O writes the downloaded document; both operands are paths."),
        P("curl_case_distinct_data_and_header_options",
            "curl -d payload -D headers.txt https://example.invalid/api",
            "Curl -d consumes non-path request data while -D consumes a header-output path."),

        // ---- Native option hardening: value- and context-sensitive cases ----
        P("tar_info_script_commands",
            "tar -F ./volume-helper.sh --info-script=./info-helper.sh "
            + "--new-volume-script ./next-volume.sh archive",
            "Tar helper hooks execute commands and safe-fail; the bare archive operand remains a path argument."),
        P("curl_data_file_references",
            "curl -d \"@request.json\" --data=@payload.bin https://example.invalid/api",
            "Curl data operands prefixed with @ read files; authored values retain the @ marker."),
        P("curl_data_stdin_reference",
            "curl -d \"@-\" https://example.invalid/api",
            "Curl @- reads stdin and is not a filesystem path."),
        P("curl_data_quoted_inline_reference",
            "curl --data='@C:\\payload file' https://example.invalid/api",
            "An adjacent quoted inline value is one native argument and preserves curl's file-read metadata."),
        P("inline_colon_backtick_path",
            "Remove-Item -Path:C:\\payload` file.txt",
            "An inline cmdlet path decodes its backtick escape before resolution."),
        P("recursion_command_outer_redirect",
            "pwsh -Command \"git status\" > outer.txt",
            "A redirect authored on a pwsh wrapper remains visible after command-string recursion."),
        P("curl_data_multiple_adjacent_fragments",
            "curl --data='@request'\" file.json\" https://example.invalid/api",
            "The complete adjacent fragment run becomes one native argument and one path-aware element."),
        P("recursion_empty_command_outer_redirect",
            "pwsh -Command \"\" > empty.txt",
            "An empty wrapped payload still surfaces its outer redirect as a redirect-only clause."),
        P("curl_data_unquoted_prefix_fragment",
            "curl --data=@request\".json\" https://example.invalid/api",
            "An unquoted equals-value prefix joins the complete adjacent native argument."),
        P("curl_data_mixed_literal_dynamic",
            "curl --data='@$HOME'\".json\" https://example.invalid/api",
            "Resolver-sensitive mixed quoting safe-fails instead of expanding literal bytes."),
        P("curl_data_transformed_literal_dynamic",
            "curl --data='@~'\"/secret.json\" https://example.invalid/api",
            "Resolver-sensitive syntax exposed after curl's @ marker is removed still safe-fails."),

        // ---- Resolver and interpolation hardening follow-up ----
        A("escaped_home_literal_path", "Backtick escaped HOME remains a literal path", "Get-Content `$HOME",
            "The backtick escape removes interpolation eligibility without erasing the authored path value."),
        A("literalpath_abbreviation_wildcard", "LiteralPath abbreviation suppresses wildcard semantics", "Get-Content -LiteralP \"*.txt\"",
            "Unambiguous parameter-prefix binding retains canonical LiteralPath identity."),
        A("unknown_cmdlet_path_semantics", "Cmdlet shape alone does not prove Path semantics", "Get-Foo -Path FileSystem::C:/safe",
            "Only a closed-table known cmdlet or alias may activate provider and parameter semantics."),
        A("null_sink_redirect", "PowerShell null sink redirect remains non-file", "Write-Output ok > $null",
            "The unescaped variable token is the PowerShell discard sink, not a filesystem target."),
        A("escaped_null_redirect", "Escaped PowerShell null text is a literal file target", "Write-Output ok > `$null",
            "Decoded text alone is insufficient: the backtick proves this is not the null sink."),
        A("native_quoted_wildcard", "Quoted native wildcard is a literal path", "git add \"*.txt\"",
            "PowerShell native argument wildcard eligibility is quote-sensitive."),
        A("cmdlet_path_wildcard", "Cmdlet Path wildcard remains a pattern", "Get-Content -Path \"*.txt\"",
            "Cmdlet Path applies wildcard semantics after quote removal, unlike native arguments."),
        A("adjacent_escaped_redirect_target", "Adjacent escaped PowerShell redirect fragments form one target", "Write-Output ok > `$HOME\".txt\"",
            "The redirect target is aggregated before provider-aware resolution."),
        A("cmdlet_index_expression", "Cmdlet index expression fails closed", "Get-Content -LiteralPath $HOME[0]",
            "PowerShell binds this as an IndexExpressionAst, not HOME plus literal suffix text."),
        A("cmdlet_colon_member_expression", "Cmdlet colon member expression fails closed", "Get-Content -Path:$HOME.Length",
            "PowerShell binds the colon tail as a MemberExpressionAst and the parser does not evaluate it."),
        A("native_member_spelling", "Spaced native member expression fails closed", "curl --output $HOME.Length https://example.invalid/api",
            "A bare variable at the start of a spaced native argument remains a PowerShell member expression; native command kind does not turn the suffix into literal text."),
        A("native_inline_member_spelling", "Native inline member-looking spelling is literal suffix text", "curl --output=$HOME.Length https://example.invalid/api",
            "The same authored fragment has native rather than cmdlet binding semantics."),
        A("ambiguous_colon_parameter", "Ambiguous colon parameter fails closed", "Get-Content -P:\"safe.txt\"",
            "-P matches multiple known parameters, so neither binding nor path mode is proved."),
        A("ambiguous_separated_parameter", "Ambiguous separated parameter fails closed", "Get-Content -P safe.txt",
            "The following token cannot safely be treated as either a bound value or a positional path."),
        A("unproved_single_letter_psdrive", "Unproved single-letter PSDrive fails closed", "Get-Content Z:\\x",
            "A single-letter drive is not proved FileSystem merely from its spelling."),
        A("unproved_psdrive_redirect", "Unproved PSDrive redirect fails closed", "Write-Output ok > Z:\\x",
            "Redirect path semantics require a proved PSDrive provider mapping."),
        A("drive_relative_path", "Drive-relative path fails closed", "Get-Content C:relative.txt",
            "C:relative.txt depends on PowerShell's per-drive current location, which parser options do not model."),
        A("drive_relative_redirect", "Drive-relative redirect fails closed", "Write-Output ok > C:relative.txt",
            "A configured C drive does not prove its drive-relative current location."),
        A("quoted_member_suffix", "Quoted member-looking suffix remains exact", "Get-Content -Path $HOME\".Length\"",
            "The quote boundary makes .Length literal text rather than a MemberExpressionAst."),
        A("dynamic_command_identity", "Opaque PowerShell command identity remains dynamic", "Get-$(Write-Output Content) /etc/passwd",
            "Adjacent aggregation preserves the opaque executable identity through VerbChain.IsDynamic."),
        A("empty_path_value", "Empty PowerShell path value fails closed", "Get-Content \"\"",
            "An empty filesystem argument is not a resolvable static path."),
        A("runtime_question_parameter_path", "Runtime PowerShell status variable fails closed", "Get-Content \"$?\"",
            "The special variable has a runtime value and cannot be reclassified as literal punctuation."),
        A("runtime_numeric_variable_path", "Runtime PowerShell numeric variable fails closed", "Get-Content \"$1\"",
            "Numeric variable identity is retained while its runtime path value remains unknown."),
        A("runtime_unicode_variable_path", "Runtime PowerShell Unicode variable fails closed", "Get-Content \"$é\"",
            "Unicode variable names are recognized expansions rather than literal filenames."),
        A("unterminated_braced_interpolation", "Unterminated PowerShell braced interpolation is unparseable", "Get-Content \"${HOME\"",
            "PowerShell reports parser errors; no compatibility path is exposed."),
        A("escaped_open_brace_literal_path", "Escaped PowerShell interpolation start remains literal", "Get-Content \"`${HOME\"",
            "The backtick escapes the dollar, so the open brace remains exact literal data."),
        A("runtime_scoped_variable_path", "Runtime PowerShell scoped variable fails closed", "Get-Content \"$global:scoped\"",
            "Scoped variable identity is retained while its runtime filesystem value remains unknown."),
        A("runtime_braced_variable_path", "Runtime PowerShell braced variable fails closed", "Get-Content \"${braced-name}\"",
            "A braced variable name is a recognized expansion rather than an exact literal filename."),

        SI("v03_mixed_list_pipeline",
            "gci | Select-Object Name && Get-Date; Get-Process",
            "A pipeline followed by && and ; pins statement-versus-pipeline structure."),

        // ---- v0.3 PowerShell command-substitution structure ----
        S("v03_substitution_multiple",
            "Write-Output $(Get-Date) $(Get-Location)",
            "Sibling subexpressions are projected in authored order before their consumer."),
        S("v03_substitution_nested",
            "Write-Output $(Get-Item $(Get-Location))",
            "Nested subexpressions project innermost commands first without losing parentage."),
        S("v03_substitution_standalone",
            "$(Write-Output Get-Date)",
            "A standalone subexpression exposes its body without inventing an invocation."),
        S("v03_substitution_call_operator",
            "& $(Write-Output Get-Date) argument",
            "The call operator exposes the producer while the computed invocation remains incomplete."),
        S("v03_substitution_current_scope_cwd",
            "Write-Output $(Set-Location C:\\sensitive && Get-Location); Get-Item child.txt",
            "A subexpression success continuation sees the target while its failure-aware outer join stays unknown."),
        S("v03_substitution_redirect",
            "Get-Content > $(Join-Path C:\\temp out.txt)",
            "A redirect subexpression is visible while the outer redirect remains incomplete."),
        S("v03_substitution_expanding_here_string",
            "Write-Output @\"\nvalue $(Get-Date)\n\"@",
            "An expanding here-string exposes its command subexpression."),
        S("v03_substitution_dynamic_host_payload",
            "pwsh -Command \"Write-Output $(Get-Date)\"",
            "Parent-scope expansion remains visible beside the complete decoded authored command."),
        S("v03_substitution_static_host_payload",
            "pwsh -Command 'Write-Output $(Get-Date)'",
            "A literal child payload is decoded and its child-scope substitution is exposed."),
        S("v03_substitution_direct_comment_boundary",
            "Write-Output $(Write-Output 'x'# )\nGet-Date)",
            "A comment after a closed quoted argument cannot terminate the containing subexpression."),
        Oos("v03_substitution_array_execution_gated",
            "Write-Output @(Get-Date)",
            "Execution-bearing array subexpressions fail closed until their expression grammar is modeled."),
        Oos("v03_substitution_hash_execution_gated",
            "Write-Output @{ value = $(Get-Date) }",
            "Execution-bearing hash literals fail closed instead of hiding their command."),
        Oos("v03_substitution_numeric_expression_gated",
            "Write-Output $(1-1)",
            "Numeric expression bodies are not fabricated into command occurrences."),
        Oos("v03_substitution_member_suffix_gated",
            "Write-Output $(Get-Date).ToString()",
            "Member access after a subexpression fails the whole result until expression suffixes are modeled."),
        Oos("v03_substitution_inner_here_string_gated",
            "Write-Output $(Write-Output @\"\nvalue\n\"@)",
            "Here-strings nested inside a subexpression remain a conservative grammar boundary."),
        E("v03_substitution_invalid_expandable_comment",
            "Write-Output \"$($(Write-Output x)# )\nGet-Date)\"",
            "Real PowerShell rejects comment termination inside this expandable-string subexpression."),
        Oos("v03_substitution_numeric_suffix_gated",
            "Write-Output $(1kb)",
            "PowerShell numeric suffixes are expression values, not command identities."),
        Oos("v03_substitution_hex_literal_gated",
            "Write-Output $(0x10)",
            "PowerShell hexadecimal literals are not fabricated into commands."),
        Oos("v03_substitution_unary_comma_gated",
            "Write-Output $(,$x)",
            "Unary comma creates an expression result and cannot be interpreted as a command."),
        Oos("v03_substitution_unary_join_gated",
            "Write-Output $(-join @('a','b'))",
            "Unary expression operators remain outside the command grammar."),
        Oos("v03_substitution_statement_array_gated",
            "Write-Output $(@(1,2,3))",
            "A literal array at statement position is data rather than an executable identity."),
        Oos("v03_substitution_later_expression_gated",
            "Write-Output $(Get-Date; 1kb)",
            "Every statement in a subexpression is checked for the command-versus-expression boundary."),
        Oos("v03_substitution_grouped_expression_gated",
            "Write-Output $((1kb))",
            "Grouping cannot bypass expression rejection inside a subexpression."),
        Oos("v03_substitution_scriptblock_value_gated",
            "Write-Output $({ Get-Date })",
            "A script-block value is not executed merely by occupying subexpression statement position."),
        S("v03_substitution_digit_command_identity",
            "Write-Output $(7z)",
            "A real digit-leading executable name remains distinct from bounded numeric literals."),
        S("v03_substitution_dynamic_cwd_poisoning",
            "Write-Output $(Set-Location $target; Get-Item child.txt); Get-Item sibling.txt",
            "Unknown current-scope location changes poison inner, consumer, and continuation attribution."),
        Oos("v03_substitution_integer_width_suffix_gated",
            "Write-Output $(0x10s)",
            "PowerShell integer-width suffixes produce numeric values rather than executable identities."),
        Oos("v03_substitution_unary_bnot_gated",
            "Write-Output $(-bnot 1)",
            "Unary bitwise negation is an expression and cannot produce a command occurrence."),
        S("v03_substitution_decimal_command_identity",
            "Write-Output $(1.0f)",
            "A decimal-looking name without a PowerShell numeric type is still an executable identity."),
        Oos("v03_substitution_unary_variable_gated",
            "Write-Output $(-$x)",
            "A sign applied to a variable is an expression rather than a sign-leading command name."),
        S("v03_substitution_dash_command_identity",
            "Write-Output $(-foo)",
            "A dash-leading word remains an executable identity when it is not a unary expression operand."),

        // ---- v0.3 foreach structure ----
        V("v03_foreach_literal_array",
            "foreach ($f in @('a.txt', 'b.txt')) { Remove-Item -LiteralPath $f }",
            "A static array exposes the loop body while policy-sensitive binding facts remain strict."),
        V("v03_foreach_pipeline_iterator",
            "foreach ($f in Get-ChildItem C:\\input) { Remove-Item -LiteralPath $f }",
            "Iterator commands and loop-body commands remain distinct authored regions."),
        V("v03_foreach_subexpression_iterator",
            "foreach ($f in $(Get-ChildItem C:\\input)) { Write-Output $f }",
            "A direct subexpression keeps substitution role inside iterator ancestry."),
        VI("v03_foreach_body_pipeline",
            "foreach ($f in @('a', 'b')) { Write-Output $f | Sort-Object }",
            "Pipeline-stage roles remain nested beneath loop-body ancestry."),
        VI("v03_foreach_parenthesized_alias",
            "Write-Output x | foreach ($_)",
            "Foreach in a pipeline command slot remains an alias with an opaque argument."),
        V("v03_foreach_call_operator_alias",
            "& foreach ($x)",
            "Foreach after a call operator remains an alias rather than a loop keyword."),
        VI("v03_foreach_numeric_pipeline_alias",
            "Write-Output x | foreach (1)",
            "A non-executing numeric argument does not turn a pipeline alias into a loop."),
        V("v03_foreach_numeric_call_operator_alias",
            "& foreach (1)",
            "A non-executing numeric argument after the call operator remains opaque."),
        V("v03_foreach_semicolon_boundary",
            "Get-Date; foreach ($x in 1) { Write-Output $x }; Get-Process",
            "A semicolon legally terminates statements around foreach."),
        V("v03_foreach_child_host_isolation",
            "pwsh -Command 'foreach ($x in 1) { Write-Output $x }'; Get-Date",
            "A loop in an isolated child host does not taint the outer continuation."),
        V("v03_foreach_following_and_or_pipeline",
            "foreach ($x in 1) { Write-Output $x }; Get-Date && Get-Process",
            "A separate pipeline chain may follow a foreach statement terminator."),
        E("v03_foreach_chain_boundary_gated",
            "Get-Date && foreach ($x in 1) { Write-Output $x }",
            "PowerShell rejects foreach as an and/or pipeline operand."),
        Oos("v03_foreach_dynamic_iterable_gated",
            "foreach ($x in $items) { Write-Output $x }",
            "Ambient iterable variables remain outside the bounded structural slice."),
        Oos("v03_foreach_body_mutation_gated",
            "foreach ($x in 1) { Set-Variable x 2 }",
            "Body mutation fails closed until PowerShell abstract state is modeled."),
        Oos("v03_foreach_alias_mutation_gated",
            "foreach ($x in 1) { Set-Alias wipe Remove-Item }; wipe file.txt",
            "Command-resolution mutation cannot leave a post-loop command marked complete."),
        Oos("v03_foreach_iterator_module_mutation_gated",
            "foreach ($x in Import-Module ./commands.psm1) { Write-Output $x }; Invoke-Thing",
            "Iterator module mutation fails closed before later command resolution can be trusted."),
        Oos("v03_foreach_provider_mutation_gated",
            "foreach ($x in 1) { Set-Item Alias:wipe Remove-Item }; wipe file.txt",
            "Alias, function, variable, and environment provider writes are runspace mutation."),
        Oos("v03_foreach_quoted_alias_mutation_gated",
            "foreach ($x in 1) { Set-Item 'Alias:wipe' Remove-Item }; wipe file.txt",
            "Quoted provider paths use decoded provenance and cannot bypass mutation gating."),
        Oos("v03_foreach_quoted_environment_mutation_gated",
            "foreach ($x in 1) { Set-Item \"Env:PATH\" C:\\tools }; tool",
            "A quoted environment provider write can change later command resolution."),
        Oos("v03_foreach_provider_qualified_iterator_mutation_gated",
            "foreach ($x in $(Set-Item 'Microsoft.PowerShell.Core\\Alias::wipe' Remove-Item; wipe victim)) { }",
            "Provider-qualified iterator mutation cannot publish a later alias invocation as complete."),
        VI("v03_foreach_isolated_exact_scalar",
            "foreach ($f in 'a.txt') { Remove-Item -LiteralPath $f }",
            "The explicit constrained-host contract permits one exact loop binding proof."),
        VI("v03_foreach_isolated_finite_array",
            "foreach ($f in @('a.txt', 'b.txt', 'a.txt')) { Write-Output $F }",
            "PowerShell variable lookup is case-insensitive and the public finite domain removes duplicates."),
        VI("v03_foreach_isolated_nested_composition",
            "foreach ($outer in 'left') { foreach ($inner in @('a','b')) { Write-Output \"$OUTER/$Inner\" } }",
            "Distinct active bindings compose without evaluating PowerShell expressions."),
        VI("v03_foreach_pipeline_objects_unknown",
            "foreach ($f in Get-ChildItem C:\\input) { Write-Output $f }",
            "Pipeline output remains an object domain and is never guessed into strings."),
        VI("v03_foreach_candidate_overflow_unknown",
            "foreach ($f in @('v01','v02','v03','v04','v05','v06','v07','v08','v09','v10','v11','v12','v13','v14','v15','v16','v17','v18','v19','v20','v21','v22','v23','v24','v25','v26','v27','v28','v29','v30','v31','v32','v33')) { Write-Output $f }",
            "The candidate cap collapses atomically to Unknown and never truncates the set."),
        OosI("v03_foreach_automatic_binding_gated",
            "foreach ($HOME in @('x')) { Write-Output $HOME }",
            "A fresh host still has built-in automatic and read-only variables."),
        VI("v03_foreach_null_object_unknown",
            "foreach ($f in @($null)) { Write-Output $f }",
            "An array containing null visits once but proves no string value."),
        VI("v03_foreach_ordered_persistent_binding",
            "foreach ($f in @('a','b','a')) { Write-Output $f }; Write-Output $f",
            "The internal visit plan retains a,b,a while the body exposes the distinct finite set and the current-scope continuation sees final a."),
        VI("v03_foreach_empty_preserves_cwd",
            "foreach ($f in @()) { Set-Location C:\\tmp }; Get-Location",
            "The unreachable authored body stays visible and complete, performs no state transition, and cannot leak parser-time cwd attribution into the continuation."),
        VI("v03_foreach_location_failure_join",
            "foreach ($d in @('C:\\a', 'C:\\b')) { Set-Location $d }; Get-ChildItem file.txt",
            "Every candidate is evaluated, but Set-Location failure and divergent successful targets force the body-input join and continuation cwd to Unknown."),
        Oos("v03_foreach_transition_budget_gated",
            "foreach ($a in @('a01','a02','a03','a04','a05','a06','a07','a08','a09','a10','a11','a12','a13','a14','a15','a16','a17')) { foreach ($b in @('b01','b02','b03','b04','b05','b06','b07','b08','b09','b10','b11','b12','b13','b14','b15','b16','b17')) { foreach ($c in @('c01','c02','c03','c04','c05','c06','c07','c08','c09','c10','c11','c12','c13','c14','c15')) { Write-Output \"$a$b$c\" } } }",
            "The valid PowerShell source exceeds the shared 4096 loop-body transition budget and fails atomically without a partial authorization projection."),
        VIE("v03_foreach_object_parallel_region",
            "Get-ChildItem | ForEach-Object -Parallel { Remove-Item $_ }",
            "Parallel exposes a concurrent child-runspace region while the pipeline object remains unresolved."),
        VIE("v03_foreach_object_parallel_process_state_escape",
            "1 | ForEach-Object -Parallel { Set-Item Env:SST_PARALLEL_PATH child }; Get-Item host.txt",
            "A process-wide child provider mutation keeps every command visible and invalidates later host facts."),
        VIE("v03_foreach_object_parallel_fresh_process_state_escape",
            "1,2 | ForEach-Object -Parallel { git status; Set-Item Env:PATH child } -ThrottleLimit 1 -UseNewRunspace",
            "Fresh child runspaces still join process-wide effects from earlier activations."),
        VIE("v03_foreach_object_parallel_rebound_process_escape",
            "1 | ForEach-Object -Parallel { Set-Alias sstSet Set-Item; sstSet Env:SST_PARALLEL_ALIAS_ESCAPE_91F62F1F child }; Get-Item host.txt",
            "A child invocation reached after command-resolution mutation may hide a process-wide environment write."),
        VIE("v03_foreach_object_parallel_runspace_global_isolated",
            "1 | ForEach-Object -Parallel { Set-Variable sstChild child -Scope Global }; Get-Item host.txt",
            "Runspace-global variable state remains isolated from the host process continuation."),
        VIE("v03_foreach_object_parallel_rebound_mutator_escape",
            "1 | ForEach-Object -Parallel { Set-Alias -Name Set-Alias -Value Set-Item; Set-Alias Env:SST_PARALLEL_REBOUND_MUTATOR_91F62F1F child } -UseNewRunspace; Get-Item host.txt",
            "An exact alias mutation can rebind a later authored mutator into a process-wide provider write within the same fresh child runspace."),
        VIE("v03_foreach_object_parallel_unrelated_rebinding_isolated",
            "1 | ForEach-Object -Parallel { Set-Alias other Set-Item; Set-Alias untouched Write-Output }; Get-Item host.txt",
            "Bounded exact-name tracking keeps unrelated runspace-local alias mutations from invalidating host process facts."),
        VIE("v03_foreach_object_parallel_function_provider_escape",
            "1 | ForEach-Object -Parallel { Set-Item Function:global:sstProviderSet { Set-Item @args }; sstProviderSet Env:SST_PARALLEL_FUNCTION_ESCAPE_91F62F1F child }; Get-Item host.txt",
            "Function-provider scope syntax is normalized to the callable name before checking whether a later child invocation can write process-wide state."),
        VIE("v03_foreach_object_parallel_double_colon_alias_escape",
            "1 | ForEach-Object -Parallel { Set-Item Alias::sstDoubleAlias Set-Item; sstDoubleAlias Env:SST_PARALLEL_DOUBLE_ALIAS_91F62F1F child }; Get-Item host.txt",
            "The provider-qualified double-colon spelling mutates the unprefixed alias name and can hide a process-wide child write."),
        VIE("v03_foreach_object_parallel_double_colon_function_escape",
            "1 | ForEach-Object -Parallel { Set-Item Function::sstDoubleFunction { Set-Item @args }; sstDoubleFunction Env:SST_PARALLEL_DOUBLE_FUNCTION_91F62F1F child }; Get-Item host.txt",
            "The provider-qualified double-colon spelling mutates the unprefixed function name and can hide a process-wide child write."),
        VIE("v03_foreach_object_parallel_provider_name_colon_precision",
            "1 | ForEach-Object -Parallel { Set-Item Alias:::sstProviderSet Set-Item; sstProviderSet Env:SST_PARALLEL_PROVIDER_COLON_91F62F1F child }; Get-Item host.txt",
            "Only the provider-qualification colon is removed; an additional authored colon remains part of the alias name and does not taint the unprefixed invocation."),
        VIE("v03_invoke_command_remote_single_target_region",
            "Invoke-Command -ComputerName server -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "One proved literal remote target executes synchronously once, while the remote body starts from unknown state and cannot taint the host continuation."),
        VIE("v03_invoke_command_remote_job_region",
            "Invoke-Command -ComputerName server -AsJob -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "An enabled remote AsJob switch proves concurrent scheduling without exporting child state."),
        VIE("v03_invoke_command_remote_disconnected_region",
            "Invoke-Command -ComputerName server -InDisconnectedSession -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "A disconnected remote invocation is concurrent even though its single target remains cardinality Once."),
        VIE("v03_invoke_command_remote_multiple_targets",
            "Invoke-Command -ComputerName server1, server2 -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "Multiple proved targets execute concurrently, but the public activation cardinality remains Unknown because it has no once-per-target discriminator."),
        VIE("v03_invoke_command_remote_inline_target_array",
            "Invoke-Command -ComputerName:server1, server2 -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "PowerShell binds a comma continuation after an inline-colon first value into the same remote target array."),
        VIE("v03_invoke_command_remote_dynamic_session",
            "Invoke-Command -Session $session -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "A runtime session collection keeps timing and cardinality Unknown while retaining the isolated remote execution boundary."),
        VIE("v03_invoke_command_remote_state_isolated",
            "Invoke-Command -ConnectionUri https://example.invalid/wsman -ScriptBlock { Set-Location /tmp; Set-Alias Measure-Command Write-Output; Set-Item Env:SST_REMOTE_CHILD child }; Get-Item host.txt; Measure-Command { Get-Date }",
            "Remote cwd, aliases, environment, and command-resolution state neither inherit local proofs nor flow into the host continuation."),
        VIE("v03_invoke_command_remote_nested_comma_scalar",
            "Invoke-Command -SSHConnection @{HostName='server,corp'} -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "A comma nested inside one literal SSH connection hashtable is not a target-array separator."),
        VIE("v03_invoke_command_remote_escaped_comma_scalar",
            "Invoke-Command -ComputerName server1`,server2 -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "A backtick-escaped comma belongs to one computer-name value and does not prove concurrent targets."),
        VIE("v03_invoke_command_remote_positional_target_array",
            "Invoke-Command server1, server2 -ScriptBlock { Get-Item child.txt }; Get-Item host.txt",
            "PowerShell binds a positional comma continuation into the ComputerName target array before the script block."),
        V("v03_redirect_multiple_explicit",
            "Get-Date > out.txt 2> err.txt",
            "Every file redirect retains authored order, source stream, operation, and exact target."),
        V("v03_redirect_dynamic_target",
            "Get-Date > $name",
            "The redirect grammar is complete while its runtime target value remains Unknown."),
        V("v03_redirect_merge_all_streams",
            "Get-Date *>&1",
            "The all-streams selector remains distinct when merged into success stream 1."),
        V("v03_redirect_merge_trailing_argument",
            "Get-Date 2>&1-",
            "PowerShell parses the merge as 2>&1 and preserves the trailing hyphen as an argument."),
        VI("v03_redirect_foreach_finite_target",
            "foreach ($f in @('one.txt', 'two.txt')) { Write-Output x > $f }",
            "An isolated bounded loop resolves the redirect target to a finite absolute path domain."),
        E("v03_redirect_input_syntax_error",
            "Get-Date < input.txt",
            "PowerShell reserves input redirection for future use."),
        E("v03_redirect_success_merge_source_error",
            "Get-Date 1>&1",
            "Success stream 1 cannot be a PowerShell merge source."),
        E("v03_redirect_non_success_merge_target_error",
            "Get-Date 2>&3",
            "PowerShell stream merges may target only success stream 1."),
        E("v03_redirect_descriptor_close_error",
            "Get-Date 2>&-",
            "PowerShell does not support Bash descriptor-close syntax."),
        V("v03_redirect_braced_null_sink",
            "Get-Date > ${null}",
            "The braced null variable is the same incomplete discard sink as $null."),
        V("v03_redirect_all_and_error_independent",
            "Get-Date *> all.txt 2> err.txt",
            "PowerShell permits all-streams and a numbered source to be redirected independently."),
        E("v03_redirect_duplicate_default_error",
            "Get-Date > a > b",
            "PowerShell rejects a second redirect of the default output stream."),
        E("v03_redirect_duplicate_default_explicit_error",
            "Get-Date > a 1> b",
            "Default output and explicit stream 1 are the same redirect source."),
        E("v03_redirect_duplicate_merge_source_error",
            "Get-Date 2>&1 2> b",
            "A merge and file redirect cannot both consume error stream 2."),
        E("v03_redirect_duplicate_all_streams_error",
            "Get-Date *> a *> b",
            "PowerShell rejects a second all-streams redirect."),
        V("v03_redirect_wrapper_joined_cwd",
            "Set-Location C:\\maybe; pwsh -Command 'Get-Date' > relative.txt",
            "A fallible cwd transition keeps the outer wrapper redirect target Unknown."),
        V("v03_redirect_encoded_wrapper_joined_cwd",
            "Set-Location C:\\maybe; pwsh -EncodedCommand RwBlAHQALQBEAGEAdABlAA== > relative.txt",
            "Encoded child syntax retains outer redirect provenance across a joined cwd."),
        VI("v03_redirect_unreachable_wrapper_binding",
            "foreach ($f in @()) { pwsh -Command 'Get-Date' > $f }",
            "An unreachable wrapper command stays complete while its redirect remains Unknown rather than borrowing a loop value."),
        VI("v03_redirect_unreachable_relative_target",
            "foreach ($x in @()) { Write-Output x > relative.txt }",
            "An unreachable relative redirect cannot retain the parser working directory as an exact target."),
        VI("v03_redirect_unreachable_absolute_target",
            "foreach ($x in @()) { Write-Output x > C:\\fixed.txt }",
            "A cwd-independent absolute redirect target remains exact on an unreachable complete authored occurrence."),
        VI("v03_redirect_wrapper_parent_binding",
            "foreach ($f in @('one.txt', 'two.txt')) { pwsh -Command 'Get-Date' > $f }",
            "The parent shell resolves an outer wrapper redirect from its bounded loop binding before child launch."),
        VI("v03_redirect_encoded_wrapper_parent_binding",
            "foreach ($f in @('one.txt', 'two.txt')) { pwsh -EncodedCommand RwBlAHQALQBEAGEAdABlAA== > $f }",
            "Encoded child syntax does not erase the parent-owned finite redirect target domain."),
        VI("v03_redirect_nested_wrapper_parent_binding",
            "foreach ($f in @('one.txt', 'two.txt')) { pwsh -Command \"pwsh -Command 'Get-Date'\" > $f }",
            "A redirect outside nested command-string wrappers retains its outermost parent binding."),
        VI("v03_redirect_nested_encoded_wrapper_parent_binding",
            "foreach ($f in @('one.txt', 'two.txt')) { pwsh -EncodedCommand " +
            B64("pwsh -EncodedCommand " + B64("Get-Date")) + " > $f }",
            "Nested encoded wrappers retain the invocation scope that owns the outer redirect."),
        VI("v03_script_block_proved_data",
            "Write-Output { Remove-Item target.txt }",
            "A proved canonical data receiver keeps a script block opaque instead of inventing a Remove-Item command occurrence."),
        VE("v03_script_block_unknown_receiver",
            "Invoke-Custom { Remove-Item target.txt }",
            "An unproved receiver over-approximates the script block as an incomplete execution region so its nested command remains visible."),
        VIE("v03_invoke_command_local_region",
            "Invoke-Command { Remove-Item secret.txt }",
            "A proved local Invoke-Command receiver exposes its positional script block as one synchronous execution region."),
        VIE("v03_module_qualified_data_exact_alias",
            "Set-Alias 'Microsoft.PowerShell.Utility\\Write-Output' Invoke-Command; " +
            "Microsoft.PowerShell.Utility\\Write-Output { Remove-Item victim.txt }",
            "An exact alias can shadow a module-qualified-looking token, so the nested command remains visible and incomplete."),
        VIE("v03_data_receiver_canonical_alias_mutation",
            "Set-Alias Write-Output Invoke-Command; " +
            "echo { Remove-Item victim.txt }",
            "A mutation of an alias canonical target also invalidates the authored alias receiver and keeps the nested command visible."),
        VIE("v03_design_static_stream_merge",
            "Get-ChildItem 2>&1",
            "Promotes stable design case pwsh-static-stream-merge."),
        VIE("v03_design_contextual_foreach_argument",
            "Write-Output foreach",
            "Promotes stable design case pwsh-contextual-foreach-argument."),
        VIE("v03_design_escaped_home_adjacent_native_fragment",
            "curl --data=@`$HOME\".json\" https://example.invalid/api",
            "Promotes stable design case pwsh-escaped-home-adjacent-native-fragment."),
        VIE("v03_design_double_quoted_escaped_home_path",
            "Get-Content \"`$HOME.txt\"",
            "Promotes stable design case pwsh-double-quoted-escaped-home-path."),
        VIE("v03_design_double_quoted_literal_expandable_composition",
            "Write-Output \"`${HOME}-$HOME\"",
            "Promotes stable design case pwsh-double-quoted-literal-expandable-composition."),
        VIE("v03_design_runtime_caret_parameter_path",
            "Get-Content \"$^\"",
            "Promotes stable design case pwsh-runtime-caret-parameter-path."),
        VIE("v03_design_runtime_dollar_parameter_path",
            "Get-Content \"$$\"",
            "Promotes stable design case pwsh-runtime-dollar-parameter-path."),
        VIE("v03_design_cmdlet_quoted_tilde_path",
            "Get-Content \"~\"",
            "Promotes stable design case pwsh-cmdlet-quoted-tilde-path."),
        VIE("v03_design_native_quoted_tilde_path",
            "curl --output \"~\" https://example.invalid",
            "Promotes stable design case pwsh-native-quoted-tilde-path."),
        VIE("v03_design_cmdlet_filesystem_provider_path",
            "Get-Content \"FileSystem::C:\\logs\\x.txt\"",
            "Promotes stable design case pwsh-cmdlet-filesystem-provider-path."),
        VIE("v03_design_native_provider_looking_path",
            "curl --output \"FileSystem::report.txt\" https://example.invalid",
            "Promotes stable design case pwsh-native-provider-looking-path."),
        VIE("v03_design_cmdlet_nonfilesystem_psdrive",
            "Get-Content \"Env:\\PATH\"",
            "Promotes stable design case pwsh-cmdlet-nonfilesystem-psdrive."),
        VIE("v03_design_cmdlet_literalpath_quoted_wildcard",
            "Get-Content -LiteralPath \"*.txt\"",
            "Promotes stable design case pwsh-cmdlet-literalpath-quoted-wildcard."),
        VIE("v03_design_native_quoted_wildcard_path",
            "curl --output \"*.txt\" https://example.invalid",
            "Promotes stable design case pwsh-native-quoted-wildcard-path."),
        VIE("v03_design_native_unquoted_tilde_path",
            "curl --output ~ https://example.invalid",
            "Promotes stable design case pwsh-native-unquoted-tilde-path."),
        VIE("v03_design_native_unquoted_wildcard_path",
            "curl --output *.txt https://example.invalid",
            "Promotes stable design case pwsh-native-unquoted-wildcard-path."),
        VIE("v03_design_cmdlet_literalpath_quoted_tilde",
            "Get-Content -LiteralPath \"~\"",
            "Promotes stable design case pwsh-cmdlet-literalpath-quoted-tilde."),
        VIE("v03_design_cmdlet_literalpath_provider",
            "Get-Content -LiteralPath \"FileSystem::C:\\logs\\x.txt\"",
            "Promotes stable design case pwsh-cmdlet-literalpath-provider."),
        VIE("v03_design_redirect_quoted_tilde",
            "Write-Output ok > \"~\"",
            "Promotes stable design case pwsh-redirect-quoted-tilde."),
        VIE("v03_design_redirect_quoted_wildcard",
            "Write-Output ok > \"*.txt\"",
            "Promotes stable design case pwsh-redirect-quoted-wildcard."),
        VIE("v03_design_redirect_filesystem_provider",
            "Write-Output ok > \"FileSystem::C:\\logs\\x.txt\"",
            "Promotes stable design case pwsh-redirect-filesystem-provider."),
        VIE("v03_design_redirect_unknown_psdrive",
            "Write-Output ok > \"ZZ:\\drive.txt\"",
            "Promotes stable design case pwsh-redirect-unknown-psdrive."),
        VIE("v03_cmdlet_unquoted_tilde_argument",
            "Get-Content ~",
            "Cmdlets receive an authored tilde string while their Path binding retains independent provider resolution."),
        VIE("v03_cmdlet_path_unquoted_wildcard_argument",
            "Get-Content -Path *.txt",
            "Path receives an exact wildcard spelling before the cmdlet applies wildcard provider semantics."),
        VIE("v03_cmdlet_literalpath_unquoted_wildcard_argument",
            "Get-Content -LiteralPath *.txt",
            "LiteralPath receives the exact wildcard spelling and suppresses wildcard provider semantics."),
        VIE("v03_native_inline_tilde_argument",
            "curl --output=~ https://example.invalid",
            "Native tilde expansion does not apply when the tilde is embedded in an option value."),
        VIE("v03_automatic_home_mutation_unknown",
            "Set-Variable HOME X -Force; Get-Content \"$HOME/x\"",
            "A forced current-runspace HOME mutation invalidates the automatic-variable value fact."),
        VIE("v03_automatic_home_mutation_preserves_native_tilde",
            "Set-Variable HOME X -Force; curl --output ~ https://example.invalid",
            "A current-runspace HOME mutation does not change the configured native tilde expansion root."),
        VIE("v03_child_process_home_after_environment_mutation",
            "Set-Item Env:HOME X; Start-Job { Get-Content \"$HOME/x\" }",
            "A fresh child process cannot reuse the configured home fact after its environment initialization input changes."),
        VIE("v03_external_script_invalidates_automatic_home",
            "./mutate.ps1; Get-Content \"$HOME/x\"",
            "An uninspected in-process PowerShell script can mutate the caller-visible AllScope HOME variable."),
        VIE("v03_explicit_hyphenated_native_path_tilde",
            "/usr/bin/my-tool ~",
            "An explicit executable path proves native argument binding even when the file name contains a hyphen."),
        VIE("v03_ambiguous_hyphenated_command_tilde",
            "git-lfs ~",
            "An unqualified hyphenated name does not prove cmdlet or native argument binding."),
        VIE("v03_ambiguous_hyphenated_command_wildcard",
            "docker-compose *.txt",
            "Wildcard argument formation remains Unknown when an unqualified name could bind as PowerShell or native."),
        VIE("v03_relative_variable_provider_home_mutation",
            "Set-Location Variable:; Set-Item HOME X -Force; Get-Content \"$HOME/x\"",
            "A relative provider target can mutate HOME after the active location changes to Variable:."),
        VIE("v03_redirect_after_automatic_home_mutation",
            "Set-Variable HOME X -Force; Write-Output hi > \"$HOME/out\"",
            "A redirect cannot retain its parser-time automatic HOME value after the current runspace mutates HOME."),
        VIE("v03_redirect_after_userprofile_environment_mutation",
            "Set-Item Env:USERPROFILE X; Write-Output hi > \"$env:USERPROFILE/out\"",
            "A redirect cannot retain its configured USERPROFILE value after process-environment mutation."),
        VIE("v03_remote_redirect_automatic_home_unknown",
            "Invoke-Command -ComputerName server { Write-Output hi > \"$HOME/out\" }",
            "A remote redirect cannot borrow the parser host's automatic HOME value."),
        VIE("v03_remote_redirect_quoted_tilde_unknown",
            "Invoke-Command -ComputerName server { Write-Output hi > \"~\" }",
            "Post-formation redirect tilde resolution remains Unknown when the remote home is unavailable."),
        VIE("v03_child_redirect_tilde_after_environment_mutation",
            "Set-Item Env:HOME X; Start-Job { Write-Output hi > \"~\" }",
            "A fresh child redirect cannot reuse configured tilde state after its home environment input changes."),
        VIE("v03_external_script_invalidates_userprofile_environment",
            "./mutate-env.ps1; Get-Content \"$env:USERPROFILE/x\"",
            "An uninspected in-process script can mutate process environment before a later path operand."),
        VIE("v03_external_script_invalidates_child_home",
            "./mutate-env.ps1; Start-Job { Get-Content \"$HOME/x\" }",
            "A child activated after an uninspected script cannot reuse the configured process-home fact."),
        VIE("v03_external_script_invalidates_location_and_binding",
            "./mutate.ps1; Get-Content relative.txt; curl ~",
            "An uninspected in-process script can persist location and global command-resolution mutations."),
        VIE("v03_encoded_child_redirect_tilde_after_environment_mutation",
            "pwsh -EncodedCommand " + B64(
                "Set-Item Env:HOME X; Start-Job { Write-Output hi > \"~\" }"),
            "A decoded inner redirect retains child process home semantics instead of borrowing the outer invocation home."),
        VIE("v03_encoded_remote_redirect_tilde_unknown",
            "pwsh -EncodedCommand " + B64(
                "Invoke-Command -ComputerName server { Write-Output hi > \"~\" }"),
            "A decoded inner remote redirect cannot reuse the outer invocation home."),
        VIE("v03_encoded_redirect_after_automatic_home_mutation",
            "pwsh -EncodedCommand " + B64(
                "Set-Variable HOME X -Force; Write-Output hi > \"$HOME/out\""),
            "A decoded inner redirect is re-evaluated after its inner runspace mutates automatic HOME."),
        VIE("v03_encoded_wrapper_command_binding_isolation",
            "pwsh -EncodedCommand " + B64("curl ~"),
            "A decoded child does not inherit the parent parser's isolated command-binding assertion."),
        VIE("v03_encoded_wrapper_clean_home_argument",
            "pwsh -EncodedCommand " + B64("Get-Content \"$HOME/x\""),
            "Decoded-wrapper reconstruction retains inner HOME provenance but does not trust an uncontrolled profile to preserve automatic HOME."),
        VIE("v03_encoded_wrapper_resets_parent_home_variable",
            "Set-Variable HOME X -Force; pwsh -EncodedCommand " +
            B64("Get-Content \"$HOME/x\""),
            "A decoded child neither inherits the parent HOME mutation nor assumes an uncontrolled profile preserves its automatic HOME value."),
        VIE("v03_encoded_wrapper_home_after_parent_environment_mutation",
            "Set-Item Env:HOME X; pwsh -EncodedCommand " +
            B64("Get-Content \"$HOME/x\""),
            "A decoded child cannot reuse configured HOME after the parent changes its process-environment input."),
        VIE("v03_encoded_wrapper_inner_home_mutation",
            "pwsh -EncodedCommand " + B64(
                "Set-Variable HOME X -Force; Get-Content \"$HOME/x\""),
            "Decoded-wrapper reconstruction preserves the inner HOME expansion so inner state mutation can invalidate it."),
        VIE("v03_nested_encoded_intermediate_redirect_owner",
            "pwsh -NoProfile -EncodedCommand " + B64(
                "pwsh -NoProfile -EncodedCommand " + B64(
                    "Set-Location /tmp/inner && Write-Output hi") +
                " > relative.txt"),
            "A redirect between nested decoded hosts resolves in the intermediate invocation rather than the deepest child."),
        VIE("v03_encoded_explicit_native_binding",
            "pwsh -EncodedCommand " + B64("/usr/bin/my-tool ~"),
            "An explicit executable path supplies authored native-binding semantics without inspecting ambient child state."),
        VIE("v03_encoded_explicit_script_binding",
            "pwsh -EncodedCommand " + B64("./tool.ps1 ~"),
            "An explicit script path supplies authored PowerShell-binding semantics without inspecting ambient child state."),
        VIE("v03_unqualified_ps1_alias_binding_unknown",
            "Set-Alias foo.ps1 Write-Output; foo.ps1 ~",
            "An unqualified .ps1-shaped name can resolve to a mutated alias, so its argument binding remains Unknown."),
        VIE("v03_encoded_unqualified_ps1_binding_unknown",
            "pwsh -EncodedCommand " + B64("foo.ps1 ~"),
            "A decoded child cannot infer authored script binding from an unqualified .ps1 suffix."),
        VIE("v03_rebound_state_mutator_invalidates_all_state",
            "Set-Alias Set-Variable Invoke-Expression; " +
            "Set-Variable 'Set-Alias evil Write-Output'; evil ~",
            "An authored state-mutator spelling reached through a rebound receiver can execute arbitrary code and invalidates every later state proof."),
        VE("v03_unknown_initial_automatic_home",
            "Write-Output \"$HOME/x\"",
            "Unknown initial state cannot equate mutable ambient automatic HOME with the configured home option."),
        VIE("v03_isolated_initial_automatic_home",
            "Write-Output \"$HOME/x\"",
            "An isolated non-interactive no-profile baseline proves the initial automatic HOME value."),
        VE("v03_unknown_initial_userprofile_environment",
            "Write-Output \"$env:USERPROFILE/x\"",
            "Unknown initial state cannot equate ambient USERPROFILE with the configured home option."),
        VIE("v03_isolated_initial_userprofile_environment",
            "Write-Output \"$env:USERPROFILE/x\"",
            "An isolated non-interactive no-profile baseline proves the initial USERPROFILE environment value."),
        VIE("v03_path_native_alias_binding_unknown",
            "Set-Alias '/usr/bin/my-tool' Write-Output; /usr/bin/my-tool ~",
            "PowerShell permits an explicit native path spelling to be shadowed by an observed alias mutation."),
        VIE("v03_path_script_alias_binding_unknown",
            "Set-Alias './tool.ps1' Write-Output; ./tool.ps1 ~",
            "PowerShell permits an explicit script path spelling to be shadowed by an observed alias mutation."),
        VIE("v03_encoded_wrapper_userprofile_profile_unknown",
            "pwsh -EncodedCommand " + B64("Get-Content \"$env:USERPROFILE/x\""),
            "An uncontrolled decoded-host profile can mutate USERPROFILE before the payload executes."),
        VE("v03_unknown_receiver_preserves_compatibility_state",
            "Invoke-Custom; Get-Content relative.txt",
            "Ambient uncertainty preserves both complete authored leaves and does not poison parser-owned cwd or path facts."),
        VIE("v03_encoded_unknown_receiver_preserves_compatibility_state",
            "pwsh -EncodedCommand " + B64(
                "foo; Write-Output hi > relative.txt"),
            "A static decoded receiver remains visible and complete without poisoning the following authored redirect or cwd facts."),
        Oos("v03_unknown_receiver_pipeline_fails_atomically",
            "Invoke-Custom { Get-Item x | Select-Object Name }",
            "An unknown receiver's unproved interior pipeline fails atomically after the unknown-state transition."),
        VIE("v03_iex_cmdlet_tilde_binding",
            "iex 'Get-Content ~'",
            "A static current-scope Invoke-Expression payload preserves cmdlet binding and keeps an unquoted tilde exact."),
        VIE("v03_iex_cmdlet_wildcard_binding",
            "iex 'Get-Content *.txt'",
            "A static current-scope Invoke-Expression payload preserves cmdlet binding and keeps an authored wildcard exact."),
        VIE("v03_iex_native_tilde_binding",
            "iex 'curl ~'",
            "A static current-scope Invoke-Expression payload preserves native binding and expands an unquoted tilde from the configured home."),
        W("v03_windows_powershell_pipeline_chain_syntax_error",
            "Get-Item a && Get-Item b",
            "Windows PowerShell 5.1 rejects PowerShell 7 pipeline-chain syntax."),
        W("v03_windows_powershell_curl_alias",
            "curl example.test",
            "Windows PowerShell 5.1 resolves curl to its default Invoke-WebRequest alias."),
        W("v03_windows_powershell_parallel_receiver_unknown",
            "ForEach-Object -Parallel { Get-Date }",
            "The PowerShell 7-only Parallel receiver contract is not borrowed by Windows PowerShell 5.1.",
            outOfScope: true),
        W("v03_windows_powershell_wmi_alias",
            "gwmi Win32_OperatingSystem",
            "Windows PowerShell 5.1 retains the removed Get-WmiObject alias contract."),
        W("v03_windows_powershell_no_get_error_alias",
            "gerr",
            "Windows PowerShell 5.1 does not borrow PowerShell 7's Get-Error alias."),
        W("v03_windows_powershell_nested_chain_foreach",
            "foreach ($x in 1) { Get-Item a && Get-Item b }",
            "Windows PowerShell 5.1 rejects pipeline-chain syntax inside a foreach body."),
        W("v03_windows_powershell_nested_chain_direct_block",
            "& { Get-Item a && Get-Item b }",
            "Windows PowerShell 5.1 rejects pipeline-chain syntax inside a direct script block."),
        W("v03_windows_powershell_nested_chain_command_block",
            "ForEach-Object -Process { Get-Item a && Get-Item b }",
            "Windows PowerShell 5.1 rejects pipeline-chain syntax inside a command-owned block."),
        W("v03_windows_powershell_nested_chain_substitution",
            "$(Get-Item a && Get-Item b)",
            "Windows PowerShell 5.1 rejects pipeline-chain syntax inside a command substitution."),
        W("v03_windows_powershell_nested_chain_child_host",
            "powershell.exe -Command 'Get-Item a && Get-Item b'",
            "A static Windows PowerShell child keeps the 5.1 grammar inside its decoded payload.",
            outOfScope: true),
        E("v03_bash_payload_stays_powershell_argument",
            "bash -c 'rm target.txt'",
            "PowerShell treats bash as an ordinary external command and does not parse its Bash payload."),
        W("v03_windows_powershell_nested_chain_invoke_expression",
            "Invoke-Expression 'Get-Item a && Get-Item b'",
            "Static current-scope recursion keeps the selected 5.1 grammar while the outer parser sees data.",
            outOfScope: true),
    };
}
