// -----------------------------------------------------------------------
// <copyright file="CorpusManifest.cs" company="Aaron Stannard">
//      Copyright (C) 2026 - 2026 Aaron Stannard <https://github.com/Aaronontheweb>
// </copyright>
// -----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ShellSyntaxTree.Tools.PwshCorpus;

internal enum ManifestTransform
{
    None,
    EncodeCommand,
    OversizedInput,
}

/// <summary>One curated PowerShell corpus input (SPEC.POWERSHELL.md §13).</summary>
internal sealed record ManifestEntry(
    string Slug,
    string RawInput,
    string Notes,
    bool OutOfScope,
    ManifestTransform Transform)
{
    /// <summary>Human-readable corpus entry name, derived from the slug.</summary>
    public string Name =>
        Slug.Length == 0
            ? Slug
            : char.ToUpperInvariant(Slug[0]) + Slug.Substring(1).Replace('_', ' ');

    /// <summary>The actual command string, after applying <see cref="Transform"/>.</summary>
    public string ResolveInput() => Transform switch
    {
        ManifestTransform.EncodeCommand =>
            "pwsh -EncodedCommand " + Convert.ToBase64String(Encoding.Unicode.GetBytes(RawInput)),
        ManifestTransform.OversizedInput =>
            RawInput + new string('a', 70 * 1024),
        _ => RawInput,
    };
}

/// <summary>
/// The hand-curated PowerShell corpus inputs. Each becomes an
/// <c>NNN_slug.json</c> entry under <c>Corpus/powershell/</c>; coverage
/// follows the SPEC.POWERSHELL.md §13 category table. The expected AST is
/// generated from <see cref="ShellSyntaxTree.PwshParser"/>; the real-pwsh
/// oracle (PwshOracleTests) independently validates every input's validity.
/// </summary>
internal static class CorpusManifest
{
    private static ManifestEntry E(string slug, string input, string notes) =>
        new(slug, input, notes, false, ManifestTransform.None);

    private static ManifestEntry Oos(string slug, string input, string notes) =>
        new(slug, input, notes, true, ManifestTransform.None);

    private static ManifestEntry Enc(string slug, string decoded, string notes, bool oos = false) =>
        new(slug, decoded, notes, oos, ManifestTransform.EncodeCommand);

    private static ManifestEntry Big(string slug, string prefix, string notes) =>
        new(slug, prefix, notes, true, ManifestTransform.OversizedInput);

    private static string B64(string s) =>
        Convert.ToBase64String(Encoding.Unicode.GetBytes(s));

    internal static IReadOnlyList<ManifestEntry> All() => new List<ManifestEntry>
    {
        // ---- Simple cmdlet (§13: ≥10) ----
        E("simple_get_date", "Get-Date", "Bare cmdlet, no args."),
        E("simple_get_childitem", "Get-ChildItem", "Bare cmdlet, no args."),
        E("simple_get_location", "Get-Location", "Bare cmdlet, no args."),
        E("simple_get_process", "Get-Process", "Bare cmdlet, no args."),
        E("simple_get_command", "Get-Command", "Bare cmdlet, no args."),
        E("simple_get_content_path", "Get-Content C:\\logs\\app.log",
            "Cmdlet with one positional path."),
        E("simple_get_item_path", "Get-Item C:\\Users\\user\\file.txt",
            "Cmdlet with a drive-qualified positional path."),
        E("simple_test_path", "Test-Path C:\\temp",
            "Test-Path FileVerb with one positional path."),
        E("simple_get_filehash", "Get-FileHash C:\\downloads\\setup.exe",
            "Get-FileHash FileVerb with one positional path."),
        E("simple_write_output", "Write-Output hello",
            "Write-Output with a non-path literal arg."),
        E("simple_resolve_path", "Resolve-Path .\\rel\\sub",
            "Resolve-Path with a relative positional path."),
        E("simple_get_member", "Get-Member", "Bare non-file cmdlet."),

        // ---- Alias resolution (§13: ≥15) — assert raw Tokens + CanonicalVerb ----
        E("alias_gci", "gci C:\\logs", "gci resolves to Get-ChildItem."),
        E("alias_ls", "ls C:\\logs", "ls resolves to Get-ChildItem."),
        E("alias_dir", "dir C:\\logs", "dir resolves to Get-ChildItem."),
        E("alias_rm", "rm C:\\temp\\old.txt", "rm resolves to Remove-Item."),
        E("alias_del", "del C:\\temp\\old.txt", "del resolves to Remove-Item."),
        E("alias_ri", "ri C:\\temp\\old.txt", "ri resolves to Remove-Item."),
        E("alias_cat", "cat C:\\logs\\app.log", "cat resolves to Get-Content."),
        E("alias_type", "type C:\\logs\\app.log", "type resolves to Get-Content."),
        E("alias_cp", "cp src.txt dst.txt", "cp resolves to Copy-Item."),
        E("alias_mv", "mv old.txt new.txt", "mv resolves to Move-Item."),
        E("alias_ni", "ni C:\\temp\\new.txt", "ni resolves to New-Item."),
        E("alias_mkdir", "mkdir C:\\temp\\newdir", "mkdir resolves to New-Item."),
        E("alias_sl", "sl C:\\repo", "sl resolves to Set-Location."),
        E("alias_echo", "echo hello", "echo resolves to Write-Output."),
        E("alias_sls", "sls error C:\\logs\\app.log", "sls resolves to Select-String."),
        E("alias_gc", "gc C:\\logs\\app.log", "gc resolves to Get-Content."),
        E("alias_gi", "gi C:\\temp\\f.txt", "gi resolves to Get-Item."),
        E("alias_select", "select Name", "select resolves to Select-Object."),

        // ---- Native command / multi-token chain (§13: ≥10) ----
        E("native_git_status", "git status", "Native git, two-token chain."),
        E("native_git_push", "git push origin main",
            "Greedy verb-chain walk absorbs origin and main."),
        E("native_dotnet_build", "dotnet build", "Native dotnet, two-token chain."),
        E("native_dotnet_ef", "dotnet ef migrations add InitialCreate",
            "Chain stops at the capitalized InitialCreate token."),
        E("native_npm_install", "npm install", "Native npm, two-token chain."),
        E("native_kubectl_get", "kubectl get pods", "Native kubectl, three-token chain."),
        E("native_docker_compose", "docker compose up", "Native docker, three-token chain."),
        E("native_python_script", "python script.py",
            "Native python with a script-file positional."),
        E("native_git_c_flag", "git -C C:\\repo status",
            "git -C consumes a directory path (shared bash flag table)."),
        E("native_git_commit", "git commit -m \"initial\"",
            "git commit; -m is not a flag-with-value so the chain stops."),
        E("native_xcopy", "xcopy C:\\src C:\\dst",
            "xcopy native file utility — one-token chain, positionals are paths."),
        E("native_where", "where git",
            "where is never aliased (§6.3 rule 3); parses as a native command."),

        // ---- Pipeline (§13: ≥15) ----
        E("pipeline_gci_rm", "gci | rm", "Two-clause alias pipeline."),
        E("pipeline_process_stop", "Get-Process | Stop-Process", "Cmdlet pipeline."),
        E("pipeline_filter_remove", "gci | ? { $_.Length -gt 1mb } | rm",
            "Three-clause pipeline with an opaque script-block filter."),
        E("pipeline_select", "Get-ChildItem | Select-Object Name", "Pipeline into Select-Object."),
        E("pipeline_selectstring", "Get-Content app.log | Select-String error",
            "Pipeline into Select-String."),
        E("pipeline_sort", "gci | Sort-Object Length", "Pipeline into Sort-Object."),
        E("pipeline_measure", "gci | measure", "Pipeline into the measure alias."),
        E("pipeline_where_block", "Get-Process | Where-Object { $_.CPU -gt 10 }",
            "Where-Object with an opaque script block."),
        E("pipeline_gci_path_remove", "gci C:\\logs | Remove-Item",
            "First clause carries a path; piped to Remove-Item."),
        E("pipeline_foreach_alias", "Get-ChildItem | foreach { $_ }",
            "foreach after a pipe is the ForEach-Object alias, not the loop keyword."),
        E("pipeline_percent_block", "gci | % { Remove-Item $_ }",
            "% alias resolves to ForEach-Object; body is opaque."),
        E("pipeline_ps_sort", "ps | sort CPU", "Two aliases piped."),
        E("pipeline_four_stage", "gci -Recurse C:\\logs | ? Name | sort | rm",
            "Four-stage pipeline mixing flags, opaque, and aliases."),
        E("pipeline_dir_gc", "dir | gc", "dir piped into gc — both aliases."),
        E("pipeline_out_file", "Get-Process | Out-File C:\\out\\procs.txt",
            "Pipeline terminating in Out-File with a path."),
        E("pipeline_format_table", "Get-Service | ft", "Pipeline into the ft alias."),
        E("pipeline_select_then_rm", "gci C:\\tmp | Select-Object -First 5 | rm",
            "Pipeline with a value-binding parameter mid-chain."),

        // ---- Compound / statement separator (§13: ≥10) ----
        E("compound_semicolon", "Get-Date; Get-Location", "Two statements joined by ;."),
        E("compound_andif", "Test-Path C:\\x && Get-ChildItem C:\\x",
            "&& pipeline-chain operator (PowerShell 7)."),
        E("compound_orif", "Test-Path C:\\x || New-Item C:\\x",
            "|| pipeline-chain operator (PowerShell 7)."),
        E("compound_three_semicolon", "gci; rm a.txt; rm b.txt", "Three ;-joined statements."),
        E("compound_mixed_operators", "Get-Date && Get-Location || Get-Process",
            "Mixed && / || chain."),
        E("compound_group", "(Get-ChildItem)", "A parenthesized pipeline marks IsSubshell."),
        E("compound_group_pipeline", "(gci C:\\tmp | Remove-Item)",
            "A group wrapping a pipeline; both clauses marked IsSubshell."),
        E("compound_newline", "Get-Date\nGet-Location",
            "A bare newline is a statement separator."),
        E("compound_andif_then_semicolon", "gci && rm a.txt; Get-Date",
            "&& then ; in one compound."),
        E("compound_group_then_clause", "(gci) ; Get-Date",
            "A group followed by a ;-joined clause."),
        E("compound_pipe_newline", "gci |\nrm",
            "A newline right after | collapses; the pipeline continues."),
        E("compound_continuation", "Get-ChildItem `\n  C:\\logs",
            "A backtick line continuation joins two physical lines."),

        // ---- Set-Location propagation (§13: ≥10) ----
        E("setloc_cd_then_git", "cd C:\\repo; git status",
            "cd attributes C:/repo to the subsequent clause."),
        E("setloc_setlocation_then_gci", "Set-Location C:\\src; Get-ChildItem",
            "Set-Location attribution to the next clause."),
        E("setloc_two_cd", "cd C:\\a; cd C:\\b; gci",
            "A later Set-Location replaces the attributed cwd."),
        E("setloc_dynamic_target", "cd $repo; gci",
            "A dynamic cd target yields dynamic attribution."),
        E("setloc_dash", "cd -; gci",
            "Set-Location - (previous location) is not statically knowable."),
        E("setloc_path_param", "Set-Location -Path C:\\proj; rm temp.txt",
            "Set-Location target taken from -Path."),
        E("setloc_through_group", "(cd C:\\sensitive); Remove-Item *",
            "Attribution propagates through a group — ( ) is not a subshell."),
        E("setloc_tilde", "cd ~; gci",
            "cd ~ attributes the home directory."),
        E("setloc_no_arg", "Set-Location; gci",
            "Set-Location with no target attributes the home directory."),
        E("setloc_relative_after_literal", "cd C:\\repo; cd sub; gci",
            "A relative cd resolves under the prior attributed cwd."),
        E("setloc_non_fs_drive", "cd HKLM:; gci",
            "cd to a non-FileSystem PSDrive yields dynamic attribution."),
        E("setloc_pushd_no_attribution", "pushd C:\\stack; gci",
            "Push-Location is a CwdVerb but adds no attribution arg (§9)."),
        E("setloc_andif", "cd C:\\repo && git status",
            "Attribution propagates across the && operator."),

        // ---- Quote handling (§13: ≥10) ----
        E("quote_single_literal", "echo 'literal $HOME'",
            "Single quotes preserve $HOME literally — no expansion."),
        E("quote_double_var", "echo \"value is $env:TEMP\"",
            "Double quotes keep $env:TEMP literal in the token value."),
        E("quote_single_path", "Get-Content 'C:\\logs\\app.log'",
            "A single-quoted path still resolves."),
        E("quote_double_spaces", "Copy-Item \"C:\\my files\\doc.txt\" \"C:\\backup\"",
            "Double-quoted paths with embedded spaces."),
        E("quote_backtick_escape", "Write-Output \"a`tb\"",
            "Backtick escape inside a double-quoted string."),
        E("quote_doubled_single", "echo 'it''s here'",
            "A doubled '' is an escaped single quote."),
        E("quote_doubled_double", "echo \"say \"\"hello\"\"\"",
            "A doubled \"\" is an escaped double quote."),
        E("quote_herestring_expandable", "Get-Content @\"\nC:\\logs\\app.log\n\"@",
            "An expandable here-string argument."),
        E("quote_herestring_literal", "Write-Output @'\n$literal text\n'@",
            "A literal here-string preserves $literal."),
        E("quote_path_with_spaces", "Get-Item \"C:\\path with spaces\\file.txt\"",
            "A double-quoted drive path with spaces."),
        E("quote_single_quoted_command", "& 'C:\\Program Files\\app\\tool.exe' run",
            "A single-quoted command name invoked with the call operator."),
        E("quote_empty_double", "Write-Output \"\"", "An empty double-quoted string."),

        // ---- Parameter binding (§13: ≥25) ----
        E("bind_path_recurse", "Get-ChildItem -Path C:\\logs -Recurse",
            "Named -Path plus the -Recurse switch."),
        E("bind_recurse_positional", "Get-ChildItem -Recurse C:\\logs",
            "-Recurse is a switch; C:\\logs stays a positional path."),
        E("bind_depth_value", "Get-ChildItem -Depth 3 C:\\logs",
            "-Depth is value-binding; 3 is its value, C:\\logs the positional."),
        E("bind_switch_positional_interleave", "Copy-Item -Force a.txt -Verbose b.txt",
            "Switches do not advance the positional index (§6.5.1)."),
        E("bind_source_destination", "Copy-Item -Path src.txt -Destination dst.txt",
            "Two path-typed parameters."),
        E("bind_literalpath", "Get-Content -LiteralPath C:\\logs\\app.log",
            "-LiteralPath value is a path."),
        E("bind_remove_recurse_force", "Remove-Item -Path C:\\temp -Recurse -Force",
            "Named path plus two trailing switches."),
        E("bind_setcontent_value", "Set-Content -Path out.txt -Value hello",
            "-Path value is a path; -Value content is not."),
        E("bind_colon_path", "Get-ChildItem -Path:C:\\logs",
            "Colon-form parameter binds its value (§6.5.3 rule 1)."),
        E("bind_colon_switch", "Get-ChildItem -Recurse:$true C:\\logs",
            "Colon-form on a switch parameter."),
        E("bind_newitem_itemtype", "New-Item -Path C:\\temp\\f.txt -ItemType File",
            "-ItemType value is a literal, not a path."),
        E("bind_filter_glob", "Get-ChildItem -Filter *.log C:\\logs",
            "-Filter value is a glob slot; C:\\logs is the positional path."),
        E("bind_selectstring_pattern", "Select-String -Pattern error -Path app.log",
            "-Pattern is not a path; -Path is."),
        E("bind_encoding", "Get-Content -Encoding UTF8 C:\\x.txt",
            "-Encoding is value-binding but its value is not a path."),
        E("bind_erroraction", "Get-ChildItem -ErrorAction SilentlyContinue C:\\logs",
            "A value-bearing common parameter."),
        E("bind_prefix_literalpath", "Get-ChildItem -lp C:\\logs",
            "-lp prefix-matches -LiteralPath (§6.5.2)."),
        E("bind_prefix_recurse", "Get-ChildItem -rec C:\\logs",
            "-rec prefix-matches the -Recurse switch."),
        E("bind_whatif_switch", "Remove-Item -WhatIf C:\\temp\\x.txt",
            "-WhatIf common switch."),
        E("bind_two_positionals", "Get-ChildItem C:\\a C:\\b",
            "Two positional paths."),
        E("bind_outfile_filepath", "Out-File -FilePath C:\\out.txt",
            "-FilePath value is a path."),
        E("bind_force_hidden", "Get-ChildItem -Force -Hidden C:\\x",
            "Two switches then a positional path."),
        E("bind_testpath_pathtype", "Test-Path -Path C:\\x -PathType Leaf",
            "-PathType value is a literal, not a path."),
        E("bind_unknown_param", "Get-ChildItem -Whatever C:\\logs",
            "An unknown parameter defaults to a switch; the positional survives."),
        E("bind_newitem_directory", "New-Item -ItemType Directory -Path C:\\newdir",
            "-Path positional path; -ItemType literal."),
        E("bind_destination_first", "Copy-Item -Destination C:\\dst -Path C:\\src",
            "Named parameters in either order."),
        E("bind_include_exclude", "Get-ChildItem -Include *.txt -Exclude *.tmp C:\\x",
            "-Include / -Exclude are glob slots."),
        E("bind_rename_newname", "Rename-Item -Path old.txt -NewName new.txt",
            "Rename-Item named parameters."),
        E("bind_gci_file_switch", "Get-ChildItem -File C:\\logs",
            "-File is a switch on Get-ChildItem (§6.5.4 collision)."),
        E("bind_importcsv_delimiter", "Import-Csv -Path data.csv -Delimiter \";\"",
            "-Delimiter is value-binding but not a path."),
        E("bind_splat", "Copy-Item @itemArgs",
            "A splat argument is opaque DynamicSkip."),
        E("bind_name_newitem", "New-Item -Name report.txt -Path C:\\out",
            "-Name is a path leaf for New-Item (§7.1)."),

        // ---- Redirect (§13: ≥10) ----
        E("redirect_out", "Get-Date > out.txt", "> stdout redirect (truncate)."),
        E("redirect_append", "Get-Date >> log.txt", ">> stdout append."),
        E("redirect_err", "Get-Process 2> err.txt", "2> stderr redirect."),
        E("redirect_err_append", "Get-Process 2>> err.txt", "2>> stderr append."),
        E("redirect_verbose", "Get-Date 3> verbose.txt", "3> verbose stream — maps lossily to Out."),
        E("redirect_warning", "Get-Date 4> warn.txt", "4> warning stream — maps lossily to Out."),
        E("redirect_debug", "Get-Date 5> debug.txt", "5> debug stream — maps lossily to Out."),
        E("redirect_information", "Get-Date 6> info.txt", "6> information stream — maps lossily to Out."),
        E("redirect_all", "Get-Date *> all.txt", "*> all-streams redirect — maps lossily to Out."),
        E("redirect_all_append", "Get-Date *>> all.txt", "*>> all-streams append."),
        E("redirect_merge_2to1", "Get-Process 2>&1", "2>&1 stream merge — target carries &1."),
        E("redirect_merge_3to1", "Get-Date 3>&1", "3>&1 stream merge."),
        E("redirect_null", "Get-Date > $null", "$null redirect target is the discard sink."),

        // ---- pwsh -Command / -EncodedCommand recursion (§13: ≥15) ----
        E("recursion_command_quoted", "pwsh -Command \"Remove-Item C:\\tmp\\x\"",
            "pwsh -Command with a quoted-string payload; inner clause surfaces wrapped."),
        E("recursion_short_c", "pwsh -c \"Get-Date\"",
            "The short -c flag is recognized as -Command."),
        E("recursion_command_pipeline", "pwsh -Command \"gci | rm\"",
            "A pipeline inside -Command surfaces as two wrapped clauses."),
        E("recursion_command_scriptblock", "pwsh -Command { Get-Date }",
            "pwsh -Command with a script-block payload."),
        E("recursion_command_bare", "pwsh -Command Remove-Item C:\\tmp\\x",
            "The bare/multi-token -Command form."),
        E("recursion_powershell_host", "powershell -Command \"Get-Process\"",
            "The powershell host name is also recognized."),
        E("recursion_command_noprofile", "pwsh -NoProfile -Command \"Get-Date\"",
            "A switch before -Command does not block recursion."),
        E("recursion_command_setlocation", "pwsh -Command \"cd C:\\x; gci\"",
            "Set-Location attribution works inside a recursed command."),
        E("recursion_command_nested", "pwsh -Command { pwsh -Command { Get-Date } }",
            "Two-level -Command recursion."),
        Enc("recursion_encoded_getdate", "Get-Date",
            "-EncodedCommand decodes base64/UTF-16LE to Get-Date."),
        Enc("recursion_encoded_remove", "Remove-Item C:\\tmp\\x",
            "-EncodedCommand decoding to a Remove-Item clause."),
        Enc("recursion_encoded_pipeline", "Get-Process | Stop-Process",
            "-EncodedCommand decoding to a pipeline."),
        Enc("recursion_encoded_controlflow", "if ($true) { Get-Date }",
            "An -EncodedCommand payload that decodes to control flow — inner unparseable propagates.", oos: true),
        E("recursion_encoded_nested", "pwsh -EncodedCommand " + B64("Get-Date"),
            "An -EncodedCommand payload that is itself a pwsh -EncodedCommand invocation."),
        Oos("recursion_encoded_bad_base64", "pwsh -EncodedCommand ###not-base64###",
            "A malformed base64 -EncodedCommand payload — the outer pwsh invocation still parses."),
        E("recursion_file_not_recursed", "pwsh -File C:\\scripts\\deploy.ps1",
            "pwsh -File is not recursion; the script path is an ordinary path arg."),
        E("recursion_iex_not_recursed", "iex \"Remove-Item C:\\x\"",
            "Invoke-Expression / iex is never recursed into (§10)."),
        Oos("recursion_depth_overflow",
            "pwsh -Command { pwsh -Command { pwsh -Command { pwsh -Command { pwsh -Command { pwsh -Command { Get-Date } } } } } }",
            "Six nested -Command levels exceed the depth-5 cap."),

        // ---- Dynamic skip (§13: ≥10) ----
        E("dynamic_call_variable", "& $exe arg1",
            "The call operator on a variable — VerbChain.IsDynamic is set."),
        E("dynamic_call_variable_noargs", "& $tool",
            "A bare dynamic call with no args."),
        E("dynamic_variable_command", "$cmd",
            "A bare variable at statement position is a dynamic command name."),
        E("dynamic_call_scriptblock", "& { Get-Date }",
            "The call operator on a script block — dynamic command."),
        E("dynamic_env_path_arg", "Get-Content $env:TEMP\\session.log",
            "An $env: reference in a path slot resolves to DynamicSkip."),
        E("dynamic_variable_path_arg", "Remove-Item $targetPath",
            "A $var in a path slot is DynamicSkip."),
        E("dynamic_subexpression_arg", "Get-Content $(Get-Location)",
            "A $( ) subexpression argument is opaque DynamicSkip."),
        E("dynamic_array_subexpression", "Write-Output @(1, 2, 3)",
            "An @( ) array subexpression argument is opaque DynamicSkip."),
        E("dynamic_glob_arg", "Get-ChildItem C:\\logs\\*.log",
            "A glob in a path slot — Kind=Glob, IsPath=true."),
        E("dynamic_comma_array", "Remove-Item a.txt,b.txt",
            "A comma-array path token is marked DynamicSkip (§8)."),
        E("dynamic_scriptblock_arg", "ForEach-Object { $_.Name }",
            "A script-block argument to ForEach-Object."),
        E("dynamic_hash_literal", "New-Item -Path C:\\x @{ Force = $true }",
            "A hash literal argument is opaque DynamicSkip."),
        E("dynamic_stop_parsing", "git --% log --oneline | findstr x",
            "The --% stop-parsing token swallows the line remainder."),

        // ---- Per-verb / per-parameter path rules (§13: ≥10) ----
        E("pathrule_copy_two_paths", "Copy-Item src.txt dst.txt",
            "Copy-Item positional 0 = source path, positional 1 = destination path."),
        E("pathrule_move_two_paths", "Move-Item old.txt archive\\old.txt",
            "Move-Item positionals are both paths."),
        E("pathrule_rename", "Rename-Item report.txt report-final.txt",
            "Rename-Item positional 0 = path, positional 1 = new name."),
        E("pathrule_selectstring_positional", "Select-String error app.log",
            "Select-String positional 0 = pattern, positional 1 = path."),
        E("pathrule_newitem_positional", "New-Item C:\\temp\\created",
            "New-Item positional 0 = path."),
        E("pathrule_setcontent_positional", "Set-Content notes.txt",
            "Set-Content positional 0 = path."),
        E("pathrule_addcontent", "Add-Content log.txt entry",
            "Add-Content positional 0 = path; the rest is content."),
        E("pathrule_registry_not_path", "Remove-Item HKLM:\\Software\\Vendor",
            "A registry-provider path is not a filesystem path (§8 step 4)."),
        E("pathrule_curl_url", "curl -o C:\\out.txt https://example.com/file",
            "Native curl: -o value is a path; the positional URL is not."),
        E("pathrule_provider_qualifier", "Get-Content FileSystem::C:\\logs\\app.log",
            "A FileSystem:: provider qualifier is stripped before resolution."),
        E("pathrule_unc_path", "Get-ChildItem \\\\internal-host.example\\share\\data",
            "A UNC path is rooted and normalized."),
        E("pathrule_home_variable", "Get-Content $HOME\\notes.txt",
            "$HOME expands to the configured home directory."),

        // ---- Unparseable: control flow, definitions, blocks, etc. (§13: ≥20) ----
        Oos("unparseable_if", "if ($true) { Get-Date }",
            "An if statement — valid PowerShell the parser declines to model."),
        Oos("unparseable_foreach", "foreach ($f in 1, 2, 3) { Write-Output $f }",
            "A foreach loop (keyword followed by '(')."),
        Oos("unparseable_while", "while ($false) { Get-Date }",
            "A while loop."),
        Oos("unparseable_for", "for ($i = 0; $i -lt 3; $i++) { Get-Date }",
            "A for loop."),
        Oos("unparseable_switch", "switch (1) { 1 { 'one' } }",
            "A switch statement."),
        Oos("unparseable_dowhile", "do { Get-Date } while ($false)",
            "A do/while loop."),
        Oos("unparseable_function", "function Show-Thing { Get-Date }",
            "A function definition."),
        Oos("unparseable_class", "class Widget { }",
            "A class definition."),
        Oos("unparseable_assignment", "$result = Get-Date",
            "An assignment statement."),
        Oos("unparseable_env_assignment", "$env:EDITOR = 'code'",
            "An $env: assignment statement."),
        Oos("unparseable_return", "return 0",
            "A return statement."),
        Oos("unparseable_throw", "throw 'boom'",
            "A throw statement."),
        Oos("unparseable_exit", "exit 0",
            "An exit statement."),
        Oos("unparseable_break", "break",
            "A bare break statement."),
        Oos("unparseable_type_literal", "[System.Math]::Sqrt(2)",
            "A bare type-literal / .NET method-call statement."),
        Oos("unparseable_trailing_amp", "git status &",
            "A trailing & background-job operator."),
        Oos("unparseable_try_catch", "try { Get-Date } catch { }",
            "A try/catch block."),
        Oos("unparseable_trap", "trap { 'caught' }",
            "A trap statement."),
        Oos("unparseable_param_block", "param($Name)",
            "A param() block."),
        Big("unparseable_oversized", "Get-ChildItem ",
            "Input over the 64 KiB parser cap — real pwsh still parses the outer command."),
        E("unparseable_unbalanced_single_quote", "Get-Content 'unbalanced",
            "An unbalanced single quote — a genuine syntax error."),
        E("unparseable_unbalanced_double_quote", "Write-Output \"unclosed",
            "An unbalanced double quote."),
        E("unparseable_stray_brace", "Get-ChildItem }",
            "A stray closing brace."),
        E("unparseable_unbalanced_paren", "Get-ChildItem )",
            "A stray closing parenthesis."),
        E("unparseable_unclosed_scriptblock", "gci | ? { $_.Name",
            "An unterminated script block."),
        E("unparseable_unterminated_block_comment", "Get-Date <# never closed",
            "An unterminated block comment."),
        E("unparseable_unclosed_subexpression", "Get-Content $(Get-Location",
            "An unterminated $( ) subexpression."),
        E("unparseable_unterminated_herestring", "Write-Output @\"\nnever closed",
            "An unterminated here-string."),

        // ---- Issue #52: hyphenated parameters and native inline values ----
        E("native_git_worktree_equals", "git --work-tree=../test add somefile",
            "Issue #52: native --flag=value stays atomic, then splits into flag and path value."),
        E("native_git_worktree_spaced", "git --work-tree repo status",
            "Issue #52: a hyphenated curated flag consumes and path-classifies its spaced value."),
        E("native_colon_option", "git --option:value status",
            "Native colon options are preserved verbatim; colon binding is cmdlet-only."),
        E("bind_hyphenated_colon", "Get-Thing -Name-Part:value",
            "A hyphenated cmdlet parameter remains one token and retains colon binding."),
        E("bind_equals_not_cmdlet_binding", "Get-Item -Path=foo bar",
            "Equals does not bind a cmdlet parameter value; the following positional remains a path."),
        E("bind_equals_colon_value_is_dynamic", "Remove-Item -Path=C:\\Windows",
            "PowerShell reads this as parameter '-Path=C:' plus argument '\\Windows' — a name that "
            + "can never bind, so the value safe-fails to DynamicSkip."),
        E("bind_question_mark_help", "Get-Help -?",
            "'-?' is a single parameter token, not a bare dash plus a '?' glob."),
    };
}
