<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Test stack -->
    <XunitVersion>2.9.2</XunitVersion>
    <XunitRunnerVersion>2.8.2</XunitRunnerVersion>
  </PropertyGroup>
  <!-- Test dependencies -->
  <ItemGroup>
    <PackageVersion Include="xunit" Version="$(XunitVersion)" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="$(XunitRunnerVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
  </ItemGroup>
  <!-- SourceLink -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.201" />
  </ItemGroup>
</Project>
